-- Insert skills (714 unique)
INSERT INTO skills (name, category) VALUES
  ('C++', 'technical'),
  ('C#', 'technical'),
  ('Data Structures and Algorithms', 'technical'),
  ('Linear Algebra', 'technical'),
  ('Engine Architecture', 'technical'),
  ('Artificial Intelligence', 'technical'),
  ('Unity', 'tool'),
  ('Unreal Engine', 'tool'),
  ('Problem Solving', 'soft_skill'),
  ('Game Mechanics Design', 'technical'),
  ('Systems Balancing', 'technical'),
  ('Level Design', 'technical'),
  ('Psychology of Play', 'technical'),
  ('Critical Thinking', 'soft_skill'),
  ('Player Empathy', 'soft_skill'),
  ('3D Modeling', 'technical'),
  ('Texturing', 'technical'),
  ('PBR Workflows', 'technical'),
  ('Rigging', 'technical'),
  ('Game Animation', 'technical'),
  ('Maya', 'tool'),
  ('ZBrush', 'tool'),
  ('Adobe Substance Painter', 'tool'),
  ('Attention to Detail', 'soft_skill'),
  ('Esports Management', 'technical'),
  ('Game Business Models', 'technical'),
  ('Player Contracts', 'technical'),
  ('Social Media Management', 'technical'),
  ('Communication', 'soft_skill'),
  ('Leadership', 'soft_skill'),
  ('Conflict Resolution', 'soft_skill'),
  ('Software Development Lifecycle', 'technical'),
  ('Machine Learning', 'technical'),
  ('Deep Learning', 'technical'),
  ('Swift', 'technical'),
  ('Kotlin', 'technical'),
  ('Git', 'tool'),
  ('Agile Methodologies', 'technical'),
  ('Analytical Thinking', 'soft_skill'),
  ('Threat Intelligence', 'technical'),
  ('Incident Response', 'technical'),
  ('Network Security', 'technical'),
  ('CompTIA Security+', 'technical'),
  ('CompTIA CySA+', 'technical'),
  ('Virtual Sandbox Environments', 'tool'),
  ('Cloud Networking', 'technical'),
  ('Virtualization Technologies', 'technical'),
  ('Systems Administration', 'technical'),
  ('Scripting', 'technical'),
  ('AWS', 'tool'),
  ('Azure', 'tool'),
  ('Troubleshooting', 'soft_skill'),
  ('HTML', 'technical'),
  ('CSS', 'technical'),
  ('JavaScript', 'technical'),
  ('React', 'technical'),
  ('Node.js', 'technical'),
  ('SQL', 'technical'),
  ('NoSQL', 'technical'),
  ('Cloud Application Deployment', 'technical'),
  ('UX Research', 'technical'),
  ('Human-Centered Design', 'technical'),
  ('Psychology of Perception', 'technical'),
  ('Wireframing', 'technical'),
  ('Prototyping', 'technical'),
  ('Figma', 'tool'),
  ('Adobe XD', 'tool'),
  ('User Testing', 'technical'),
  ('Empathy', 'soft_skill'),
  ('Storyboarding', 'technical'),
  ('Animation', 'technical'),
  ('Compositing', 'technical'),
  ('Adobe Creative Cloud', 'tool'),
  ('Maxon One', 'tool'),
  ('Nuke', 'tool'),
  ('Creativity', 'soft_skill'),
  ('Motion Graphics', 'technical'),
  ('3D for Motion Design', 'technical'),
  ('Live Event Design', 'technical'),
  ('Projection Mapping', 'technical'),
  ('After Effects', 'tool'),
  ('Cinema 4D', 'tool'),
  ('Time Management', 'soft_skill'),
  ('Branding & Identity', 'technical'),
  ('Logo Design', 'technical'),
  ('Typography', 'technical'),
  ('Print Design', 'technical'),
  ('Packaging Design', 'technical'),
  ('Digital Publishing', 'technical'),
  ('Adobe Creative Suite', 'tool'),
  ('Set Operations', 'technical'),
  ('Lighting', 'technical'),
  ('Camera Operation', 'technical'),
  ('Video Editing', 'technical'),
  ('Visual Effects', 'technical'),
  ('4K Digital Cinema Cameras', 'tool'),
  ('Teamwork', 'soft_skill'),
  ('Adaptability', 'soft_skill'),
  ('Electronic Field Production', 'technical'),
  ('Documentary Shooting', 'technical'),
  ('Data Management', 'technical'),
  ('Solo Production', 'technical'),
  ('Digital Workflow', 'technical'),
  ('Self-Direction', 'soft_skill'),
  ('Scriptwriting', 'technical'),
  ('Television Writing', 'technical'),
  ('Transmedia Writing', 'technical'),
  ('Writing for Games', 'technical'),
  ('Storytelling', 'soft_skill'),
  ('Research', 'soft_skill'),
  ('Multimedia Storytelling', 'technical'),
  ('Media Research', 'technical'),
  ('Media Sociology', 'technical'),
  ('Integrated Media Campaigns', 'technical'),
  ('Strategic Thinking', 'soft_skill'),
  ('Audience Analysis', 'soft_skill'),
  ('Vocal Training', 'technical'),
  ('On-Camera Delivery', 'technical'),
  ('Sports Digital Production', 'technical'),
  ('Public Speaking', 'soft_skill'),
  ('Composure Under Pressure', 'soft_skill'),
  ('Sports Knowledge', 'soft_skill'),
  ('Studio Engineering', 'technical'),
  ('Signal Flow', 'technical'),
  ('Mixing Techniques', 'technical'),
  ('Audio Post-Production', 'technical'),
  ('Sound Design', 'technical'),
  ('Foley', 'technical'),
  ('Large-Format Consoles', 'tool'),
  ('Pro Tools', 'tool'),
  ('Active Listening', 'soft_skill'),
  ('Project Studio Workflow', 'technical'),
  ('Game Audio Production', 'technical'),
  ('Adaptive Music Implementation', 'technical'),
  ('Digital Audio Workstation', 'tool'),
  ('Audio Interface', 'tool'),
  ('Client Communication', 'soft_skill'),
  ('Music Composition', 'technical'),
  ('Musical Structure and Analysis', 'technical'),
  ('Songwriting', 'technical'),
  ('Musical Arrangement', 'technical'),
  ('Instrumentation', 'technical'),
  ('Orchestration', 'technical'),
  ('DAW Software', 'tool'),
  ('Collaboration', 'soft_skill'),
  ('Live Sound Systems', 'technical'),
  ('Intelligent Lighting Programming', 'technical'),
  ('Video Wall Management', 'technical'),
  ('Power Distribution', 'technical'),
  ('Stage Management', 'technical'),
  ('Line Array Systems', 'tool'),
  ('Lighting Consoles', 'tool'),
  ('Business Law', 'technical'),
  ('Finance', 'technical'),
  ('Management', 'technical'),
  ('Entertainment Business Models', 'technical'),
  ('Organizational Skills', 'soft_skill'),
  ('Networking', 'soft_skill'),
  ('Artist Management', 'technical'),
  ('Music Copyright', 'technical'),
  ('Music Publishing', 'technical'),
  ('Contract Negotiation', 'technical'),
  ('Streaming Revenue Models', 'technical'),
  ('Negotiation', 'soft_skill'),
  ('Relationship Building', 'soft_skill'),
  ('Digital Analytics', 'technical'),
  ('Search Engine Optimization', 'technical'),
  ('Social Media Marketing', 'technical'),
  ('Campaign Management', 'technical'),
  ('Google Analytics', 'tool'),
  ('SEMrush', 'tool'),
  ('Fan Engagement', 'technical'),
  ('Social Media Methods', 'technical'),
  ('Sports Sales', 'technical'),
  ('Sponsorship Management', 'technical'),
  ('Community Building', 'soft_skill'),
  ('Sales Skills', 'soft_skill'),
  ('Enthusiasm', 'soft_skill'),
  ('EPA Section 608 Certification', 'technical'),
  ('Thermodynamics', 'technical'),
  ('Soldering and Brazing', 'technical'),
  ('Electrical Troubleshooting', 'technical'),
  ('Refrigerant Handling', 'technical'),
  ('Schematic Reading', 'technical'),
  ('HVAC Excellence Certification', 'technical'),
  ('Psychrometrics', 'technical'),
  ('Light Commercial Refrigeration', 'technical'),
  ('Heat Pump Systems', 'technical'),
  ('Humidity Control', 'technical'),
  ('Complex Diagnostics', 'technical'),
  ('NCCER Electrical Level 1 & 2', 'technical'),
  ('National Electrical Code (NEC)', 'technical'),
  ('Conduit Bending', 'technical'),
  ('Three-Phase Power Systems', 'technical'),
  ('OSHA Safety Standards', 'technical'),
  ('Blueprint Reading', 'technical'),
  ('AWS Certification', 'technical'),
  ('SMAW (Stick Welding)', 'technical'),
  ('GMAW (MIG Welding)', 'technical'),
  ('GTAW (TIG Welding)', 'technical'),
  ('Thermal Cutting', 'technical'),
  ('AutoCAD', 'tool'),
  ('Revit', 'tool'),
  ('Autodesk Certified User', 'technical'),
  ('Building Information Modeling (BIM)', 'technical'),
  ('2D/3D Drafting', 'technical'),
  ('Technical Drawing', 'technical'),
  ('OSHA 10 Certification', 'technical'),
  ('NCCER Core', 'technical'),
  ('Carpentry', 'technical'),
  ('Masonry', 'technical'),
  ('Site Layout', 'technical'),
  ('ASE Medium-Heavy Truck Certification', 'technical'),
  ('Diesel Engine Overhaul', 'technical'),
  ('Air Brake Systems', 'technical'),
  ('Hydraulic Systems', 'technical'),
  ('Emissions Control Systems', 'technical'),
  ('Electronic Diagnostics', 'technical'),
  ('ASE A1 (Engine Repair)', 'technical'),
  ('ASE A4 (Suspension/Steering)', 'technical'),
  ('ASE A5 (Brakes)', 'technical'),
  ('ASE A6 (Electrical)', 'technical'),
  ('NATEF Standards', 'technical'),
  ('Under-Car Systems', 'technical'),
  ('ASE A2 (Automatic Transmission)', 'technical'),
  ('ASE A3 (Manual Drivetrain)', 'technical'),
  ('ASE A7 (HVAC)', 'technical'),
  ('ASE A8 (Engine Performance)', 'technical'),
  ('Advanced Diagnostics', 'technical'),
  ('Drivability Troubleshooting', 'technical'),
  ('I-CAR Certification', 'technical'),
  ('ASE Collision Repair', 'technical'),
  ('Frame Straightening', 'technical'),
  ('Paint Application', 'technical'),
  ('Damage Analysis', 'technical'),
  ('Panel Repair', 'technical'),
  ('CDL Class A', 'technical'),
  ('ELDT Compliance', 'technical'),
  ('Vehicle Inspection', 'technical'),
  ('Backing Maneuvers', 'technical'),
  ('DOT Regulations', 'technical'),
  ('Defensive Driving', 'soft_skill'),
  ('CMA/RMA Certification', 'technical'),
  ('Phlebotomy', 'technical'),
  ('EKG Administration', 'technical'),
  ('Medical Coding', 'technical'),
  ('Pharmacology', 'technical'),
  ('Patient Care', 'soft_skill'),
  ('Florida Expanded Functions Certificate', 'technical'),
  ('CDA Certification', 'technical'),
  ('Dental Radiography', 'technical'),
  ('Chairside Assisting', 'technical'),
  ('Infection Control', 'technical'),
  ('Patient Communication', 'soft_skill'),
  ('CST Certification', 'technical'),
  ('Sterile Field Maintenance', 'technical'),
  ('Surgical Instrumentation', 'technical'),
  ('Anatomy and Physiology', 'technical'),
  ('Surgical Procedures', 'technical'),
  ('CPhT Certification', 'technical'),
  ('Sterile Compounding', 'technical'),
  ('Medication Chemistry', 'technical'),
  ('Pharmacy Law', 'technical'),
  ('Inventory Management', 'technical'),
  ('Customer Service', 'soft_skill'),
  ('MBLEx Licensure', 'technical'),
  ('Deep Tissue Massage', 'technical'),
  ('Neuromuscular Therapy', 'technical'),
  ('Anatomy and Kinesiology', 'technical'),
  ('Hydrotherapy', 'technical'),
  ('Client Relations', 'soft_skill'),
  ('CMAA Certification', 'technical'),
  ('Medical Transcription', 'technical'),
  ('Health Information Management', 'technical'),
  ('Medical Billing/Coding', 'technical'),
  ('Microsoft Office', 'tool'),
  ('LPN State License', 'technical'),
  ('Medical-Surgical Nursing', 'technical'),
  ('Pediatric Nursing', 'technical'),
  ('Geriatric Care', 'technical'),
  ('Patient Advocacy', 'soft_skill'),
  ('CNA State License', 'technical'),
  ('Vital Signs Monitoring', 'technical'),
  ('Activities of Daily Living (ADL)', 'technical'),
  ('Patient Hygiene', 'technical'),
  ('Basic Nursing Skills', 'technical'),
  ('Compassion', 'soft_skill'),
  ('Cisco CCNA', 'technical'),
  ('Microsoft Certified Systems Administrator', 'technical'),
  ('Server Administration', 'technical'),
  ('Network Configuration', 'technical'),
  ('Virtualization', 'technical'),
  ('CompTIA A+', 'technical'),
  ('CompTIA Network+', 'technical'),
  ('Windows/Linux Configuration', 'technical'),
  ('Mobile Device Management (MDM)', 'technical'),
  ('Hardware Troubleshooting', 'technical'),
  ('Adobe Certified Professional', 'technical'),
  ('Graphic Design', 'technical'),
  ('Web Design', 'technical'),
  ('Visual Communication', 'soft_skill'),
  ('Autodesk Maya', 'tool'),
  ('Autodesk Certification', 'technical'),
  ('Motion Capture', 'technical'),
  ('Florida State Cosmetology License', 'technical'),
  ('Hair Design', 'technical'),
  ('Chemical Processes', 'technical'),
  ('Skin Care', 'technical'),
  ('Salon Management', 'technical'),
  ('ServSafe Certification', 'technical'),
  ('Classical Cooking Techniques', 'technical'),
  ('Food Sanitation', 'technical'),
  ('Kitchen Management', 'technical'),
  ('Menu Planning', 'technical'),
  ('NCLEX-RN Certification', 'technical'),
  ('Patient Assessment', 'technical'),
  ('Medication Administration', 'technical'),
  ('Clinical Procedures', 'technical'),
  ('Nursing Leadership', 'technical'),
  ('Evidence-Based Practice', 'technical'),
  ('Nursing Research', 'technical'),
  ('Community Health', 'technical'),
  ('Team Management', 'soft_skill'),
  ('Strategic Planning', 'soft_skill'),
  ('RRT Certification', 'technical'),
  ('Cardiopulmonary Physiology', 'technical'),
  ('Ventilator Management', 'technical'),
  ('Critical Care Medicine', 'technical'),
  ('Arterial Blood Gas Analysis', 'technical'),
  ('Patient Education', 'soft_skill'),
  ('NPTAE Certification', 'technical'),
  ('Musculoskeletal Rehabilitation', 'technical'),
  ('Therapeutic Exercise', 'technical'),
  ('Gait Training', 'technical'),
  ('Patient Motivation', 'soft_skill'),
  ('RHIT Certification', 'technical'),
  ('ICD-10 Coding', 'technical'),
  ('CPT Coding', 'technical'),
  ('Health Data Analysis', 'technical'),
  ('Healthcare Statistics', 'technical'),
  ('HIPAA Compliance', 'technical'),
  ('Healthcare Finance', 'technical'),
  ('Health Law and Ethics', 'technical'),
  ('U.S. Healthcare System', 'technical'),
  ('Clinical Leadership', 'soft_skill'),
  ('Staff Management', 'soft_skill'),
  ('Quality Improvement', 'technical'),
  ('Certified Ethical Hacker (CEH)', 'technical'),
  ('Penetration Testing', 'technical'),
  ('Vulnerability Assessment', 'technical'),
  ('Network Defense', 'technical'),
  ('Enterprise Networking', 'technical'),
  ('Security Analysis', 'technical'),
  ('Firewall Configuration', 'technical'),
  ('Intrusion Detection', 'technical'),
  ('Operating Systems Security', 'technical'),
  ('Cybersecurity Operations', 'technical'),
  ('Digital Forensics', 'technical'),
  ('Information Security Management', 'technical'),
  ('Cloud Security', 'technical'),
  ('Risk Assessment', 'technical'),
  ('Python', 'technical'),
  ('Operating Systems', 'technical'),
  ('Ticketing Systems', 'tool'),
  ('CCNA', 'technical'),
  ('Router Configuration', 'technical'),
  ('Switch Configuration', 'technical'),
  ('Network Troubleshooting', 'technical'),
  ('AWS Fundamentals', 'tool'),
  ('Azure Administration', 'tool'),
  ('Network Infrastructure', 'technical'),
  ('Cloud Computing', 'technical'),
  ('Documentation', 'soft_skill'),
  ('Cost Estimating', 'technical'),
  ('Construction Safety', 'technical'),
  ('Materials Management', 'technical'),
  ('Project Scheduling', 'technical'),
  ('Team Coordination', 'soft_skill'),
  ('General Contractor Licensure', 'technical'),
  ('Construction Project Management', 'technical'),
  ('Construction Cost Estimating', 'technical'),
  ('Construction Materials and Methods', 'technical'),
  ('Contract Administration', 'technical'),
  ('Construction Methods', 'technical'),
  ('Building Codes', 'technical'),
  ('Site Safety', 'technical'),
  ('Materials Handling', 'technical'),
  ('Quality Inspection', 'technical'),
  ('Space Planning', 'technical'),
  ('Visual Presentation', 'technical'),
  ('Color Theory', 'technical'),
  ('NCIDQ Certification', 'technical'),
  ('Evidence-Based Design', 'technical'),
  ('Building Codes and Regulations', 'technical'),
  ('Project Management', 'soft_skill'),
  ('Client Presentation', 'soft_skill'),
  ('PLC Programming', 'technical'),
  ('Fluid Power Systems', 'technical'),
  ('Robotics Maintenance', 'technical'),
  ('Industrial Troubleshooting', 'technical'),
  ('PMMI Mechatronics Certification', 'technical'),
  ('Industrial Processes', 'technical'),
  ('Quality Control', 'technical'),
  ('Equipment Maintenance', 'technical'),
  ('Process Improvement', 'technical'),
  ('ASE Master Technician Certification', 'technical'),
  ('Ford ASSET / GM ASEP Training', 'technical'),
  ('Hybrid/Electric Vehicle Technology', 'technical'),
  ('Engine Diagnostics', 'technical'),
  ('Automotive Electronics', 'technical'),
  ('FDLE Certification', 'technical'),
  ('Law Enforcement Procedures', 'technical'),
  ('Firearms Proficiency', 'technical'),
  ('Defensive Tactics', 'technical'),
  ('Report Writing', 'technical'),
  ('Crisis De-escalation', 'soft_skill'),
  ('Criminology', 'technical'),
  ('Criminal Law', 'technical'),
  ('Criminal Investigation', 'technical'),
  ('Evidence Collection', 'technical'),
  ('Interview Techniques', 'technical'),
  ('Public Policy', 'technical'),
  ('Administrative Law', 'technical'),
  ('Crisis Management', 'technical'),
  ('Budget Administration', 'technical'),
  ('Strategic Leadership', 'soft_skill'),
  ('Agency Management', 'soft_skill'),
  ('Fire Officer Supervisor Certification', 'technical'),
  ('Fire Prevention', 'technical'),
  ('Building Construction for Fire Service', 'technical'),
  ('Fire Tactics', 'technical'),
  ('Incident Command', 'technical'),
  ('Team Leadership', 'soft_skill'),
  ('ABA Approved Program', 'technical'),
  ('Legal Research and Writing', 'technical'),
  ('Civil Litigation', 'technical'),
  ('Torts', 'technical'),
  ('Florida E-Filing Portal', 'tool'),
  ('Case Management Software', 'tool'),
  ('Global Supply Chain Management', 'technical'),
  ('Human Resources Management', 'technical'),
  ('Business Finance', 'technical'),
  ('Organizational Leadership', 'soft_skill'),
  ('Change Management', 'soft_skill'),
  ('SHRM Competencies', 'technical'),
  ('Employment Law', 'technical'),
  ('Compensation and Benefits', 'technical'),
  ('Recruitment', 'technical'),
  ('HRIS Systems', 'tool'),
  ('Interpersonal Skills', 'soft_skill'),
  ('Opportunity Analysis', 'technical'),
  ('Entrepreneurial Marketing', 'technical'),
  ('Business Planning', 'technical'),
  ('Financial Management', 'technical'),
  ('Florida Teaching Certification (K-6)', 'technical'),
  ('Reading Endorsement', 'technical'),
  ('ESOL Endorsement', 'technical'),
  ('Lesson Planning', 'technical'),
  ('Classroom Management', 'soft_skill'),
  ('Differentiated Instruction', 'technical'),
  ('Florida ESE Certification (K-12)', 'technical'),
  ('IEP Development', 'technical'),
  ('Behavior Management', 'technical'),
  ('Patience and Empathy', 'soft_skill'),
  ('AutoCAD Civil 3D', 'tool'),
  ('MicroStation', 'tool'),
  ('Site Design', 'technical'),
  ('Permitting and Compliance', 'technical'),
  ('Construction Inspection', 'technical'),
  ('Technical Writing', 'soft_skill'),
  ('Project Documentation', 'technical'),
  ('RFI Management', 'technical'),
  ('Submittal Processing', 'technical'),
  ('Safety Compliance', 'technical'),
  ('Subcontractor Management', 'soft_skill'),
  ('Spanish Communication', 'soft_skill'),
  ('HEC-RAS', 'tool'),
  ('ICPR', 'tool'),
  ('SWMM', 'tool'),
  ('Hydraulic Modeling', 'technical'),
  ('Stormwater Management', 'technical'),
  ('Environmental Regulations', 'technical'),
  ('Optical Design', 'technical'),
  ('Lens Assembly Design', 'technical'),
  ('Laser Systems', 'technical'),
  ('Optical Bench Setup', 'technical'),
  ('Fiber Optics', 'technical'),
  ('LiDAR Technology', 'technical'),
  ('Scanning Electron Microscopy (SEM)', 'tool'),
  ('X-Ray Diffraction (XRD)', 'tool'),
  ('Spectroscopy', 'tool'),
  ('Composites Analysis', 'technical'),
  ('Semiconductor Processing', 'technical'),
  ('Corrosion Control', 'technical'),
  ('Guest Recovery', 'soft_skill'),
  ('Crew Scheduling', 'technical'),
  ('Bilingual Communication (Spanish)', 'soft_skill'),
  ('Operational Leadership', 'soft_skill'),
  ('Event Logistics', 'technical'),
  ('Vendor Management', 'technical'),
  ('Room Block Coordination', 'technical'),
  ('Sales and Negotiation', 'soft_skill'),
  ('Budget Management', 'technical'),
  ('Business Presentation', 'soft_skill'),
  ('Data Analysis', 'technical'),
  ('Team Collaboration', 'soft_skill'),
  ('ARGUS', 'tool'),
  ('Excel Financial Modeling', 'tool'),
  ('Cash Flow Analysis', 'technical'),
  ('Property Valuation', 'technical'),
  ('Market Analysis', 'technical'),
  ('Hematology Testing', 'technical'),
  ('Microbiology', 'technical'),
  ('Clinical Chemistry', 'technical'),
  ('ASCP Certification', 'technical'),
  ('Microscopy', 'tool'),
  ('Clinical Research (CCRP)', 'technical'),
  ('Laboratory Techniques', 'technical'),
  ('Data Collection', 'technical'),
  ('Scientific Writing', 'soft_skill'),
  ('Regulatory Compliance', 'technical'),
  ('Speech Therapy Techniques', 'technical'),
  ('Hearing Assessment', 'technical'),
  ('Bilingual Therapy (Spanish)', 'soft_skill'),
  ('Patient Documentation', 'technical'),
  ('Therapy Plan Implementation', 'technical'),
  ('Empathy and Patience', 'soft_skill'),
  ('UI/UX Design', 'technical'),
  ('Game Testing', 'technical'),
  ('Portfolio Development', 'soft_skill'),
  ('Blender', 'tool'),
  ('Character Rigging', 'technical'),
  ('Texturing and Lighting', 'technical'),
  ('ABA Therapy', 'technical'),
  ('Case Documentation', 'technical'),
  ('Crisis Intervention', 'technical'),
  ('Research Methods', 'technical'),
  ('Community Engagement', 'soft_skill'),
  ('Archival Research', 'technical'),
  ('Grant Writing', 'technical'),
  ('Historical Analysis', 'technical'),
  ('Data Synthesis', 'soft_skill'),
  ('Public Presentation', 'soft_skill'),
  ('Archaeological Survey', 'technical'),
  ('GIS Mapping', 'tool'),
  ('Ethnographic Research', 'technical'),
  ('Artifact Analysis', 'technical'),
  ('Field Documentation', 'technical'),
  ('Cross-Cultural Communication', 'soft_skill'),
  ('Policy Research', 'technical'),
  ('Legislative Analysis', 'technical'),
  ('Constituent Relations', 'soft_skill'),
  ('Political Writing', 'soft_skill'),
  ('Case Management', 'technical'),
  ('Family Assessment', 'technical'),
  ('Child Welfare Regulations', 'technical'),
  ('Advocacy', 'soft_skill'),
  ('Java', 'technical'),
  ('Cloud Architecture (AWS)', 'technical'),
  ('Machine Learning Concepts', 'technical'),
  ('Agile Methodology', 'process'),
  ('Windows Server Admin', 'technical'),
  ('Hardware Diagnostics', 'technical'),
  ('SQL Querying', 'technical'),
  ('HTML5 / CSS3', 'technical'),
  ('Debugging', 'technical'),
  ('Algorithm Logic', 'technical'),
  ('Cisco IOS', 'tool'),
  ('Subnetting', 'technical'),
  ('Protocol Analysis', 'tool'),
  ('Structured Cabling', 'technical'),
  ('Vulnerability Scanning', 'technical'),
  ('Compliance', 'technical'),
  ('Linux Security', 'technical'),
  ('Backup & Recovery', 'technical'),
  ('Data Modeling', 'technical'),
  ('Database Security', 'technical'),
  ('Performance Tuning', 'technical'),
  ('Hardware Repair', 'technical'),
  ('OS Installation', 'technical'),
  ('Remote Support', 'technical'),
  ('Cabling Standards', 'technical'),
  ('Basic Routing', 'technical'),
  ('Connectivity Diagnostics', 'technical'),
  ('Network Mapping', 'tool'),
  ('JavaScript (Basic)', 'technical'),
  ('CMS Management', 'tool'),
  ('Responsive Design', 'technical'),
  ('SEO Basics', 'technical'),
  ('Circuit Analysis', 'technical'),
  ('Cleanroom Protocol', 'technical'),
  ('Matlab/Simulink', 'tool'),
  ('Soldering', 'technical'),
  ('Oscilloscope Usage', 'tool'),
  ('Multimeter Proficiency', 'tool'),
  ('Troubleshooting Logic', 'technical'),
  ('AutoCAD / SolidWorks', 'tool'),
  ('Metrology', 'technical'),
  ('Lean Manufacturing', 'process'),
  ('Hydraulics/Pneumatics', 'technical'),
  ('Materials Science', 'technical'),
  ('Brake Systems', 'technical'),
  ('Electrical Systems', 'technical'),
  ('Suspension & Steering', 'technical'),
  ('Safety Protocols', 'technical'),
  ('NEC Code Compliance', 'technical'),
  ('Circuit Installation', 'technical'),
  ('Safety/Lockout-Tagout', 'technical'),
  ('EPA Certification', 'technical'),
  ('Brazing/Soldering', 'technical'),
  ('Airflow Dynamics', 'technical'),
  ('Welding Processes', 'technical'),
  ('Metal Properties', 'technical'),
  ('Health Informatics', 'tool'),
  ('Healthcare Law/Ethics', 'technical'),
  ('Human Resources', 'technical'),
  ('EHR Systems', 'tool'),
  ('Anatomy/Physiology', 'technical'),
  ('Physics of Sound', 'technical'),
  ('Patient Positioning', 'technical'),
  ('Pathology Recognition', 'technical'),
  ('Image Annotation', 'technical'),
  ('Periodontal Therapy', 'technical'),
  ('Local Anesthesia', 'technical'),
  ('ICD-10 / CPT Coding', 'technical'),
  ('EHR Management', 'tool'),
  ('Data Privacy', 'technical'),
  ('Medical Terminology', 'technical'),
  ('Radiation Safety', 'technical'),
  ('Anatomy', 'technical'),
  ('Equipment Operation', 'technical'),
  ('Image Evaluation', 'technical'),
  ('Arterial Blood Gas', 'technical'),
  ('Airway Management', 'technical'),
  ('Manual Therapy', 'technical'),
  ('Modalities', 'tool'),
  ('Advanced Life Support', 'technical'),
  ('Triage', 'technical'),
  ('Patient Transport', 'technical'),
  ('ICD-10 / CPT', 'technical'),
  ('Insurance Verification', 'technical'),
  ('Billing Software', 'tool'),
  ('Anatomy/Terminology', 'technical'),
  ('Scheduling Software', 'tool'),
  ('Office Systems', 'technical'),
  ('Venipuncture', 'technical'),
  ('Specimen Handling', 'technical'),
  ('Patient Interaction', 'soft_skill'),
  ('Vitals Monitoring', 'technical'),
  ('Wound Care', 'technical'),
  ('Data Analytics', 'technical'),
  ('Digital Recruitment', 'technical'),
  ('QuickBooks / Excel', 'tool'),
  ('Tax Regulation', 'technical'),
  ('General Ledger', 'technical'),
  ('Financial Reporting', 'technical'),
  ('Business Communication', 'soft_skill'),
  ('Marketing Principles', 'technical'),
  ('Office Software', 'tool'),
  ('Financial Basics', 'technical'),
  ('Scheduling', 'technical'),
  ('Event Planning', 'technical'),
  ('Grant Administration', 'technical'),
  ('Budgeting', 'technical'),
  ('HR Management', 'technical'),
  ('Fire Dynamics', 'technical'),
  ('Building Construction', 'technical'),
  ('Hazardous Materials', 'technical'),
  ('Tactics & Strategy', 'technical'),
  ('Legal Research', 'tool'),
  ('Legal Writing', 'technical'),
  ('E-Filing', 'tool'),
  ('Legal Terminology', 'technical'),
  ('Office Management', 'technical'),
  ('Document Prep', 'technical'),
  ('Ethics', 'technical'),
  ('CPR / First Aid', 'technical'),
  ('Transport', 'technical'),
  ('Vitals', 'technical'),
  ('Physical Fitness', 'technical'),
  ('PPE Usage', 'technical'),
  ('Hose Handling', 'technical'),
  ('Search & Rescue', 'technical'),
  ('Ladder Operations', 'technical'),
  ('Food Safety', 'technical'),
  ('Culinary Techniques', 'technical'),
  ('Inventory Control', 'technical'),
  ('Staff Supervision', 'soft_skill'),
  ('Hospitality Law', 'technical'),
  ('PMS Systems', 'tool'),
  ('Revenue Management', 'technical'),
  ('Cinematography', 'technical'),
  ('Set Protocol', 'technical'),
  ('Sound Recording', 'technical'),
  ('Production Management', 'technical'),
  ('Adobe Suite', 'tool'),
  ('Branding', 'technical'),
  ('Print Production', 'technical'),
  ('CAD / Revit', 'tool'),
  ('Knife Skills', 'technical'),
  ('Cooking Methods', 'technical'),
  ('Sanitation', 'technical'),
  ('Mise en Place', 'technical'),
  ('Recipe Follow', 'technical'),
  ('Social Media', 'technical'),
  ('Child Development', 'technical'),
  ('Curriculum', 'technical'),
  ('Observation', 'technical'),
  ('Family Communication', 'soft_skill'),
  ('Supervision', 'technical'),
  ('Play Facilitation', 'technical'),
  ('Hygiene', 'technical'),
  ('Regulations', 'technical'),
  ('Resource Referral', 'technical')
ON CONFLICT (name) DO NOTHING;

