-- Insert program to career path mappings (546 links)
INSERT INTO program_career_paths (program_key, school, career_path_id)
SELECT links.program_key, links.school, cp.id
FROM (VALUES
  ('fullsail_game_development', 'fullsail', 'Junior Gameplay Programmer'),
  ('fullsail_game_development', 'fullsail', 'Software Engineer'),
  ('fullsail_game_development', 'fullsail', 'Tools Programmer'),
  ('fullsail_game_development', 'fullsail', 'Simulation Engineer'),
  ('fullsail_game_design', 'fullsail', 'Junior Level Designer'),
  ('fullsail_game_design', 'fullsail', 'System Designer'),
  ('fullsail_game_design', 'fullsail', 'Quest Designer'),
  ('fullsail_game_design', 'fullsail', 'Quality Assurance Analyst'),
  ('fullsail_game_art', 'fullsail', 'Junior 3D Environment Artist'),
  ('fullsail_game_art', 'fullsail', 'Prop Artist'),
  ('fullsail_game_art', 'fullsail', 'Character Artist'),
  ('fullsail_game_art', 'fullsail', 'Technical Artist'),
  ('fullsail_game_business_esports', 'fullsail', 'Esports Event Coordinator'),
  ('fullsail_game_business_esports', 'fullsail', 'Team Manager'),
  ('fullsail_game_business_esports', 'fullsail', 'Community Manager'),
  ('fullsail_game_business_esports', 'fullsail', 'Sponsorship Sales Associate'),
  ('fullsail_computer_science', 'fullsail', 'Junior Software Engineer'),
  ('fullsail_computer_science', 'fullsail', 'Mobile Application Developer'),
  ('fullsail_computer_science', 'fullsail', 'Full Stack Developer'),
  ('fullsail_computer_science', 'fullsail', 'AI Specialist'),
  ('fullsail_cybersecurity', 'fullsail', 'Information Security Analyst'),
  ('fullsail_cybersecurity', 'fullsail', 'Security Operations Center Analyst'),
  ('fullsail_cybersecurity', 'fullsail', 'Vulnerability Assessor'),
  ('fullsail_information_technology', 'fullsail', 'IT Support Specialist'),
  ('fullsail_information_technology', 'fullsail', 'Network Administrator'),
  ('fullsail_information_technology', 'fullsail', 'Cloud Support Associate'),
  ('fullsail_web_development', 'fullsail', 'Web Developer'),
  ('fullsail_web_development', 'fullsail', 'Front-End Engineer'),
  ('fullsail_web_development', 'fullsail', 'Back-End Developer'),
  ('fullsail_user_experience', 'fullsail', 'UX Designer'),
  ('fullsail_user_experience', 'fullsail', 'UI Designer'),
  ('fullsail_user_experience', 'fullsail', 'Product Designer'),
  ('fullsail_computer_animation', 'fullsail', '3D Animator'),
  ('fullsail_computer_animation', 'fullsail', 'Rigger'),
  ('fullsail_computer_animation', 'fullsail', 'Lighter'),
  ('fullsail_computer_animation', 'fullsail', 'Compositor'),
  ('fullsail_digital_arts_design', 'fullsail', 'Motion Graphics Artist'),
  ('fullsail_digital_arts_design', 'fullsail', 'Broadcast Designer'),
  ('fullsail_digital_arts_design', 'fullsail', 'Multimedia Artist'),
  ('fullsail_graphic_design', 'fullsail', 'Junior Graphic Designer'),
  ('fullsail_graphic_design', 'fullsail', 'Production Artist'),
  ('fullsail_graphic_design', 'fullsail', 'Visual Designer'),
  ('fullsail_film', 'fullsail', 'Production Assistant'),
  ('fullsail_film', 'fullsail', 'Camera Assistant'),
  ('fullsail_film', 'fullsail', 'Grip'),
  ('fullsail_film', 'fullsail', 'Assistant Editor'),
  ('fullsail_film', 'fullsail', 'Videographer'),
  ('fullsail_digital_cinematography', 'fullsail', 'Content Creator'),
  ('fullsail_digital_cinematography', 'fullsail', 'Corporate Videographer'),
  ('fullsail_digital_cinematography', 'fullsail', 'Digital Media Producer'),
  ('fullsail_creative_writing', 'fullsail', 'Junior Copywriter'),
  ('fullsail_creative_writing', 'fullsail', 'Script Reader'),
  ('fullsail_creative_writing', 'fullsail', 'Narrative Designer'),
  ('fullsail_creative_writing', 'fullsail', 'Editorial Assistant'),
  ('fullsail_media_communications', 'fullsail', 'Social Media Coordinator'),
  ('fullsail_media_communications', 'fullsail', 'Public Relations Assistant'),
  ('fullsail_media_communications', 'fullsail', 'Content Strategist'),
  ('fullsail_sportscasting', 'fullsail', 'Multimedia Journalist'),
  ('fullsail_sportscasting', 'fullsail', 'Sports Reporter'),
  ('fullsail_sportscasting', 'fullsail', 'Play-by-Play Announcer'),
  ('fullsail_sportscasting', 'fullsail', 'Production Assistant'),
  ('fullsail_recording_arts', 'fullsail', 'Audio Engineer'),
  ('fullsail_recording_arts', 'fullsail', 'Studio Runner'),
  ('fullsail_recording_arts', 'fullsail', 'Live Sound Technician'),
  ('fullsail_recording_arts', 'fullsail', 'AV Technician'),
  ('fullsail_audio_production', 'fullsail', 'Freelance Sound Designer'),
  ('fullsail_audio_production', 'fullsail', 'Game Audio Specialist'),
  ('fullsail_audio_production', 'fullsail', 'Podcast Producer'),
  ('fullsail_music_production', 'fullsail', 'Music Producer'),
  ('fullsail_music_production', 'fullsail', 'Composer'),
  ('fullsail_music_production', 'fullsail', 'Arranger'),
  ('fullsail_music_production', 'fullsail', 'Beatmaker'),
  ('fullsail_show_production', 'fullsail', 'Live Sound Engineer'),
  ('fullsail_show_production', 'fullsail', 'Lighting Technician'),
  ('fullsail_show_production', 'fullsail', 'AV Installer'),
  ('fullsail_entertainment_business', 'fullsail', 'Production Coordinator'),
  ('fullsail_entertainment_business', 'fullsail', 'Talent Assistant'),
  ('fullsail_entertainment_business', 'fullsail', 'Event Coordinator'),
  ('fullsail_entertainment_business', 'fullsail', 'Marketing Assistant'),
  ('fullsail_music_business', 'fullsail', 'Artist Manager'),
  ('fullsail_music_business', 'fullsail', 'Touring Coordinator'),
  ('fullsail_music_business', 'fullsail', 'Publishing Assistant'),
  ('fullsail_music_business', 'fullsail', 'Ticket Sales Representative'),
  ('fullsail_digital_marketing', 'fullsail', 'SEO Specialist'),
  ('fullsail_digital_marketing', 'fullsail', 'Digital Marketing Coordinator'),
  ('fullsail_digital_marketing', 'fullsail', 'Social Media Manager'),
  ('fullsail_sports_marketing_media', 'fullsail', 'Sports Marketing Coordinator'),
  ('fullsail_sports_marketing_media', 'fullsail', 'Ticket Sales Representative'),
  ('fullsail_sports_marketing_media', 'fullsail', 'Brand Ambassador'),
  ('fullsail_sports_marketing_media', 'fullsail', 'Sports Marketing Assistant'),
  ('orange_heating_ventilation_airconditioningrefrigeration_1', 'orange', 'HVAC Helper'),
  ('orange_heating_ventilation_airconditioningrefrigeration_1', 'orange', 'Entry-Level HVAC Technician'),
  ('orange_heating_ventilation_airconditioningrefrigeration_1', 'orange', 'Maintenance Technician'),
  ('orange_heating_ventilation_airconditioningrefrigeration_1', 'orange', 'Refrigeration Helper'),
  ('orange_heating_ventilation_airconditioningrefrigeration_2', 'orange', 'Commercial HVAC Technician'),
  ('orange_heating_ventilation_airconditioningrefrigeration_2', 'orange', 'HVAC Service Technician'),
  ('orange_heating_ventilation_airconditioningrefrigeration_2', 'orange', 'Refrigeration Technician'),
  ('orange_heating_ventilation_airconditioningrefrigeration_2', 'orange', 'Heat Pump Specialist'),
  ('orange_electricity', 'orange', 'Electrician Helper'),
  ('orange_electricity', 'orange', 'Residential Electrician'),
  ('orange_electricity', 'orange', 'Commercial Electrician'),
  ('orange_electricity', 'orange', 'Electrical Apprentice'),
  ('orange_welding_technology', 'orange', 'Welder Helper'),
  ('orange_welding_technology', 'orange', 'Shielded Metal Arc Welder'),
  ('orange_welding_technology', 'orange', 'MIG Welder'),
  ('orange_welding_technology', 'orange', 'Pipe Welder'),
  ('orange_computeraided_drawing_and_modeling', 'orange', 'CAD Technician'),
  ('orange_computeraided_drawing_and_modeling', 'orange', 'Architectural Drafter'),
  ('orange_computeraided_drawing_and_modeling', 'orange', 'BIM Technician'),
  ('orange_computeraided_drawing_and_modeling', 'orange', 'Civil CAD Drafter'),
  ('orange_building_construction_technologies', 'orange', 'Construction Laborer'),
  ('orange_building_construction_technologies', 'orange', 'Carpenter Helper'),
  ('orange_building_construction_technologies', 'orange', 'Concrete Finisher'),
  ('orange_building_construction_technologies', 'orange', 'Mason Helper'),
  ('orange_diesel_systems_technician', 'orange', 'Diesel Engine Mechanic Helper'),
  ('orange_diesel_systems_technician', 'orange', 'Diesel Technician'),
  ('orange_diesel_systems_technician', 'orange', 'Heavy Equipment Technician'),
  ('orange_diesel_systems_technician', 'orange', 'Diesel Hydraulics Technician'),
  ('orange_master_automotive_service_technology_1', 'orange', 'Entry-Level Automotive Technician'),
  ('orange_master_automotive_service_technology_1', 'orange', 'Brake Technician'),
  ('orange_master_automotive_service_technology_1', 'orange', 'Suspension Technician'),
  ('orange_master_automotive_service_technology_1', 'orange', 'Lube Technician'),
  ('orange_master_automotive_service_technology_2', 'orange', 'Automotive Diagnostician'),
  ('orange_master_automotive_service_technology_2', 'orange', 'Line Technician'),
  ('orange_master_automotive_service_technology_2', 'orange', 'Transmission Technician'),
  ('orange_master_automotive_service_technology_2', 'orange', 'ASE Master Technician'),
  ('orange_automotive_collision_technology_technician', 'orange', 'Collision Repair Technician'),
  ('orange_automotive_collision_technology_technician', 'orange', 'Auto Body Painter'),
  ('orange_automotive_collision_technology_technician', 'orange', 'Frame Technician'),
  ('orange_automotive_collision_technology_technician', 'orange', 'Estimator'),
  ('orange_commercial_vehicle_driving', 'orange', 'Local Truck Driver'),
  ('orange_commercial_vehicle_driving', 'orange', 'Over-the-Road (OTR) Driver'),
  ('orange_commercial_vehicle_driving', 'orange', 'Delivery Driver'),
  ('orange_commercial_vehicle_driving', 'orange', 'Tanker Driver'),
  ('orange_medical_assisting', 'orange', 'Medical Assistant'),
  ('orange_medical_assisting', 'orange', 'Clinical Medical Assistant'),
  ('orange_medical_assisting', 'orange', 'Phlebotomist'),
  ('orange_medical_assisting', 'orange', 'Care Coordinator'),
  ('orange_dental_assisting_technology_and_management', 'orange', 'Dental Assistant'),
  ('orange_dental_assisting_technology_and_management', 'orange', 'Expanded Functions Dental Assistant'),
  ('orange_dental_assisting_technology_and_management', 'orange', 'Dental Radiographer'),
  ('orange_dental_assisting_technology_and_management', 'orange', 'Orthodontic Assistant'),
  ('orange_surgical_technology', 'orange', 'Surgical Technologist'),
  ('orange_surgical_technology', 'orange', 'Scrub Tech'),
  ('orange_surgical_technology', 'orange', 'Operating Room Technician'),
  ('orange_surgical_technology', 'orange', 'Surgical First Assistant'),
  ('orange_pharmacy_technician', 'orange', 'Pharmacy Technician'),
  ('orange_pharmacy_technician', 'orange', 'Hospital Pharmacy Technician'),
  ('orange_pharmacy_technician', 'orange', 'Compounding Technician'),
  ('orange_pharmacy_technician', 'orange', 'Pharmacy Inventory Specialist'),
  ('orange_massage_therapy', 'orange', 'Licensed Massage Therapist'),
  ('orange_massage_therapy', 'orange', 'Spa Massage Therapist'),
  ('orange_massage_therapy', 'orange', 'Medical Massage Therapist'),
  ('orange_massage_therapy', 'orange', 'Sports Massage Therapist'),
  ('orange_medical_administrative_specialist', 'orange', 'Medical Administrative Assistant'),
  ('orange_medical_administrative_specialist', 'orange', 'Medical Office Manager'),
  ('orange_medical_administrative_specialist', 'orange', 'Unit Secretary'),
  ('orange_medical_administrative_specialist', 'orange', 'Medical Billing Specialist'),
  ('orange_practical_nursing', 'orange', 'Licensed Practical Nurse'),
  ('orange_practical_nursing', 'orange', 'Long-Term Care LPN'),
  ('orange_practical_nursing', 'orange', 'Clinic LPN'),
  ('orange_practical_nursing', 'orange', 'Home Health LPN'),
  ('orange_patient_care_assistant', 'orange', 'Certified Nursing Assistant'),
  ('orange_patient_care_assistant', 'orange', 'Patient Care Technician'),
  ('orange_patient_care_assistant', 'orange', 'Home Health Aide'),
  ('orange_patient_care_assistant', 'orange', 'Nursing Home Aide'),
  ('orange_enterprise_network_and_server_support_technology', 'orange', 'Network Technician'),
  ('orange_enterprise_network_and_server_support_technology', 'orange', 'SOC Analyst'),
  ('orange_enterprise_network_and_server_support_technology', 'orange', 'Server Administrator'),
  ('orange_enterprise_network_and_server_support_technology', 'orange', 'Systems Support Specialist'),
  ('orange_enterprise_desktop_and_mobile_support_technology', 'orange', 'Help Desk Technician'),
  ('orange_enterprise_desktop_and_mobile_support_technology', 'orange', 'Desktop Support Specialist'),
  ('orange_enterprise_desktop_and_mobile_support_technology', 'orange', 'IT Support Technician'),
  ('orange_enterprise_desktop_and_mobile_support_technology', 'orange', 'Mobile Device Support Specialist'),
  ('orange_digital_mediamultimedia_design', 'orange', 'Graphic Designer'),
  ('orange_digital_mediamultimedia_design', 'orange', 'Web Designer'),
  ('orange_digital_mediamultimedia_design', 'orange', 'Video Editor'),
  ('orange_digital_mediamultimedia_design', 'orange', 'Content Creator'),
  ('orange_3d_animation_technology', 'orange', '3D Animator'),
  ('orange_3d_animation_technology', 'orange', '3D Modeler'),
  ('orange_3d_animation_technology', 'orange', 'Simulation Developer'),
  ('orange_3d_animation_technology', 'orange', 'Texture Artist'),
  ('orange_cosmetology', 'orange', 'Cosmetologist'),
  ('orange_cosmetology', 'orange', 'Hair Stylist'),
  ('orange_cosmetology', 'orange', 'Salon Manager'),
  ('orange_cosmetology', 'orange', 'Color Specialist'),
  ('orange_professional_culinary_arts_hospitality', 'orange', 'Line Cook'),
  ('orange_professional_culinary_arts_hospitality', 'orange', 'Prep Cook'),
  ('orange_professional_culinary_arts_hospitality', 'orange', 'Sous Chef'),
  ('orange_professional_culinary_arts_hospitality', 'orange', 'Pastry Cook'),
  ('seminole_nursing', 'seminole', 'Registered Nurse'),
  ('seminole_nursing', 'seminole', 'Medical-Surgical Nurse'),
  ('seminole_nursing', 'seminole', 'Psychiatric Nurse'),
  ('seminole_nursing', 'seminole', 'Maternal-Child Nurse'),
  ('seminole_nursing', 'seminole', 'Charge Nurse'),
  ('seminole_nursing', 'seminole', 'Nurse Manager'),
  ('seminole_nursing', 'seminole', 'Community Health Nurse'),
  ('seminole_nursing', 'seminole', 'Clinical Nurse Leader'),
  ('seminole_respiratory_care', 'seminole', 'Respiratory Therapist'),
  ('seminole_respiratory_care', 'seminole', 'Critical Care Respiratory Therapist'),
  ('seminole_respiratory_care', 'seminole', 'Pediatric Respiratory Therapist'),
  ('seminole_respiratory_care', 'seminole', 'Pulmonary Function Technologist'),
  ('seminole_physical_therapist_assistant', 'seminole', 'Physical Therapist Assistant'),
  ('seminole_physical_therapist_assistant', 'seminole', 'Rehabilitation Aide'),
  ('seminole_physical_therapist_assistant', 'seminole', 'Home Health PTA'),
  ('seminole_physical_therapist_assistant', 'seminole', 'Outpatient Clinic PTA'),
  ('seminole_health_information_technology', 'seminole', 'Registered Health Information Technician'),
  ('seminole_health_information_technology', 'seminole', 'Medical Coder'),
  ('seminole_health_information_technology', 'seminole', 'Health Data Analyst'),
  ('seminole_health_information_technology', 'seminole', 'Medical Records Specialist'),
  ('seminole_health_sciences', 'seminole', 'Practice Manager'),
  ('seminole_health_sciences', 'seminole', 'Clinical Coordinator'),
  ('seminole_health_sciences', 'seminole', 'Health Services Manager'),
  ('seminole_health_sciences', 'seminole', 'Healthcare Administrator'),
  ('seminole_cybersecurity', 'seminole', 'Security Analyst (Entry)'),
  ('seminole_cybersecurity', 'seminole', 'SOC Analyst'),
  ('seminole_cybersecurity', 'seminole', 'Penetration Tester (Junior)'),
  ('seminole_cybersecurity', 'seminole', 'Network Security Technician'),
  ('seminole_information_systems_technology_cybersecurity', 'seminole', 'Information Security Analyst'),
  ('seminole_information_systems_technology_cybersecurity', 'seminole', 'Network Security Administrator'),
  ('seminole_information_systems_technology_cybersecurity', 'seminole', 'Cybersecurity Technician'),
  ('seminole_information_systems_technology_cybersecurity', 'seminole', 'Security Operations Specialist'),
  ('seminole_information_systems_technology', 'seminole', 'Information Security Manager'),
  ('seminole_information_systems_technology', 'seminole', 'Digital Forensics Analyst'),
  ('seminole_information_systems_technology', 'seminole', 'Cybersecurity Operations Manager'),
  ('seminole_information_systems_technology', 'seminole', 'Cloud Security Architect'),
  ('seminole_computer_programming_and_analysis', 'seminole', 'Junior Programmer'),
  ('seminole_computer_programming_and_analysis', 'seminole', 'Web Developer'),
  ('seminole_computer_programming_and_analysis', 'seminole', 'Simulation Programmer'),
  ('seminole_computer_programming_and_analysis', 'seminole', 'Data Analyst'),
  ('seminole_network_support_technician', 'seminole', 'Help Desk Technician'),
  ('seminole_network_support_technician', 'seminole', 'Desktop Support Specialist'),
  ('seminole_network_support_technician', 'seminole', 'IT Support Technician'),
  ('seminole_network_infrastructure', 'seminole', 'Network Technician'),
  ('seminole_network_infrastructure', 'seminole', 'Junior Network Administrator'),
  ('seminole_network_infrastructure', 'seminole', 'Cable Installer'),
  ('seminole_network_systems_technology', 'seminole', 'Network Administrator'),
  ('seminole_network_systems_technology', 'seminole', 'Cloud Support Associate'),
  ('seminole_network_systems_technology', 'seminole', 'Systems Administrator'),
  ('seminole_network_systems_technology', 'seminole', 'Computer User Support Specialist'),
  ('seminole_construction_management', 'seminole', 'Assistant Superintendent'),
  ('seminole_construction_management', 'seminole', 'Materials Estimator'),
  ('seminole_construction_management', 'seminole', 'Field Engineer'),
  ('seminole_construction_management', 'seminole', 'Project Coordinator'),
  ('seminole_construction', 'seminole', 'Project Manager'),
  ('seminole_construction', 'seminole', 'Construction Superintendent'),
  ('seminole_construction', 'seminole', 'General Contractor'),
  ('seminole_construction', 'seminole', 'Construction Cost Estimator'),
  ('seminole_building_construction_technology', 'seminole', 'Construction Technician'),
  ('seminole_building_construction_technology', 'seminole', 'Construction Inspector'),
  ('seminole_building_construction_technology', 'seminole', 'Site Coordinator'),
  ('seminole_interior_design', 'seminole', 'Junior Interior Designer'),
  ('seminole_interior_design', 'seminole', 'Design Assistant'),
  ('seminole_interior_design', 'seminole', 'CAD Drafter'),
  ('seminole_interior_design', 'seminole', 'Showroom Consultant'),
  ('seminole_interior_design', 'seminole', 'Licensed Interior Designer'),
  ('seminole_interior_design', 'seminole', 'Healthcare Interior Designer'),
  ('seminole_interior_design', 'seminole', 'Corporate Interior Designer'),
  ('seminole_interior_design', 'seminole', 'Design Project Manager'),
  ('seminole_mechatronics', 'seminole', 'Mechatronics Technician'),
  ('seminole_mechatronics', 'seminole', 'Automation Technician'),
  ('seminole_mechatronics', 'seminole', 'PLC Technician'),
  ('seminole_mechatronics', 'seminole', 'Robotics Technician'),
  ('seminole_engineering_technology', 'seminole', 'Electro-Mechanical Technician'),
  ('seminole_engineering_technology', 'seminole', 'Industrial Engineering Technician'),
  ('seminole_engineering_technology', 'seminole', 'Quality Control Technician'),
  ('seminole_engineering_technology', 'seminole', 'Manufacturing Technician'),
  ('seminole_automotive_engineering_technology', 'seminole', 'Automotive Technician'),
  ('seminole_automotive_engineering_technology', 'seminole', 'Master Automotive Technician'),
  ('seminole_automotive_engineering_technology', 'seminole', 'Service Advisor'),
  ('seminole_automotive_engineering_technology', 'seminole', 'Hybrid/EV Technician'),
  ('seminole_criminal_justice_law_enforcement_academy', 'seminole', 'Police Officer'),
  ('seminole_criminal_justice_law_enforcement_academy', 'seminole', 'Deputy Sheriff'),
  ('seminole_criminal_justice_law_enforcement_academy', 'seminole', 'Corrections Officer'),
  ('seminole_criminal_justice_technology', 'seminole', 'Police Officer'),
  ('seminole_criminal_justice_technology', 'seminole', 'Crime Scene Technician'),
  ('seminole_criminal_justice_technology', 'seminole', 'Probation Officer'),
  ('seminole_criminal_justice_technology', 'seminole', 'Criminal Investigator'),
  ('seminole_public_safety_administration', 'seminole', 'Police Lieutenant'),
  ('seminole_public_safety_administration', 'seminole', 'Fire Captain'),
  ('seminole_public_safety_administration', 'seminole', 'Emergency Management Director'),
  ('seminole_public_safety_administration', 'seminole', 'Public Safety Director'),
  ('seminole_fire_science_technology', 'seminole', 'Firefighter'),
  ('seminole_fire_science_technology', 'seminole', 'Fire Officer Supervisor'),
  ('seminole_fire_science_technology', 'seminole', 'Fire Inspector'),
  ('seminole_fire_science_technology', 'seminole', 'Fire Prevention Specialist'),
  ('seminole_legal_assistantparalegal_studies', 'seminole', 'Paralegal'),
  ('seminole_legal_assistantparalegal_studies', 'seminole', 'Legal Assistant'),
  ('seminole_legal_assistantparalegal_studies', 'seminole', 'Litigation Support Specialist'),
  ('seminole_legal_assistantparalegal_studies', 'seminole', 'Legal Document Specialist'),
  ('seminole_management_and_organizational_leadership', 'seminole', 'Operations Manager'),
  ('seminole_management_and_organizational_leadership', 'seminole', 'General Manager'),
  ('seminole_management_and_organizational_leadership', 'seminole', 'Management Analyst'),
  ('seminole_management_and_organizational_leadership', 'seminole', 'Business Owner'),
  ('seminole_human_resources_administrator', 'seminole', 'HR Assistant'),
  ('seminole_human_resources_administrator', 'seminole', 'Recruiter'),
  ('seminole_human_resources_administrator', 'seminole', 'Benefits Coordinator'),
  ('seminole_human_resources_administrator', 'seminole', 'HR Coordinator'),
  ('seminole_entrepreneurship', 'seminole', 'Small Business Owner'),
  ('seminole_entrepreneurship', 'seminole', 'Freelance Consultant'),
  ('seminole_entrepreneurship', 'seminole', 'Business Development Representative'),
  ('seminole_entrepreneurship', 'seminole', 'Startup Founder'),
  ('seminole_elementary_education', 'seminole', 'Elementary School Teacher'),
  ('seminole_elementary_education', 'seminole', 'Reading Specialist'),
  ('seminole_elementary_education', 'seminole', 'ESOL Teacher'),
  ('seminole_elementary_education', 'seminole', 'Curriculum Coordinator'),
  ('seminole_exceptional_student_education', 'seminole', 'ESE Teacher'),
  ('seminole_exceptional_student_education', 'seminole', 'Special Education Coordinator'),
  ('seminole_exceptional_student_education', 'seminole', 'Behavior Specialist'),
  ('seminole_exceptional_student_education', 'seminole', 'Inclusion Specialist'),
  ('ucf_civil_engineering', 'ucf', 'Civil Engineer I'),
  ('ucf_civil_engineering', 'ucf', 'Transportation Analyst'),
  ('ucf_civil_engineering', 'ucf', 'Field Engineer'),
  ('ucf_civil_engineering', 'ucf', 'Site Design Engineer'),
  ('ucf_construction_engineering', 'ucf', 'Construction Project Engineer'),
  ('ucf_construction_engineering', 'ucf', 'Assistant Superintendent'),
  ('ucf_construction_engineering', 'ucf', 'Cost Estimator'),
  ('ucf_construction_engineering', 'ucf', 'Field Engineer'),
  ('ucf_environmental_engineering', 'ucf', 'Environmental Engineer I'),
  ('ucf_environmental_engineering', 'ucf', 'Water Resources Engineer'),
  ('ucf_environmental_engineering', 'ucf', 'Compliance Specialist'),
  ('ucf_environmental_engineering', 'ucf', 'Remediation Engineer'),
  ('ucf_photonic_science_and_engineering', 'ucf', 'Photonics Engineer'),
  ('ucf_photonic_science_and_engineering', 'ucf', 'Optical Systems Engineer'),
  ('ucf_photonic_science_and_engineering', 'ucf', 'Laser Engineer'),
  ('ucf_photonic_science_and_engineering', 'ucf', 'Test Engineer'),
  ('ucf_materials_science_and_engineering', 'ucf', 'Materials Engineer'),
  ('ucf_materials_science_and_engineering', 'ucf', 'Process Engineer'),
  ('ucf_materials_science_and_engineering', 'ucf', 'Failure Analyst'),
  ('ucf_materials_science_and_engineering', 'ucf', 'Quality Engineer'),
  ('ucf_theme_park_and_attraction_management', 'ucf', 'Operations Supervisor'),
  ('ucf_theme_park_and_attraction_management', 'ucf', 'Guest Experience Manager'),
  ('ucf_theme_park_and_attraction_management', 'ucf', 'Area Manager'),
  ('ucf_theme_park_and_attraction_management', 'ucf', 'Attraction Operations Supervisor'),
  ('ucf_event_management', 'ucf', 'Event Coordinator'),
  ('ucf_event_management', 'ucf', 'Catering Sales Manager'),
  ('ucf_event_management', 'ucf', 'Venue Coordinator'),
  ('ucf_event_management', 'ucf', 'Meeting Planner Assistant'),
  ('ucf_integrated_business', 'ucf', 'Business Analyst'),
  ('ucf_integrated_business', 'ucf', 'Project Coordinator'),
  ('ucf_integrated_business', 'ucf', 'Sales Representative'),
  ('ucf_integrated_business', 'ucf', 'Operations Analyst'),
  ('ucf_real_estate', 'ucf', 'Real Estate Analyst'),
  ('ucf_real_estate', 'ucf', 'Property Manager'),
  ('ucf_real_estate', 'ucf', 'Commercial Real Estate Agent'),
  ('ucf_real_estate', 'ucf', 'Leasing Consultant'),
  ('ucf_medical_laboratory_sciences', 'ucf', 'Medical Laboratory Scientist'),
  ('ucf_medical_laboratory_sciences', 'ucf', 'Clinical Laboratory Technologist'),
  ('ucf_medical_laboratory_sciences', 'ucf', 'Lab Technologist'),
  ('ucf_medical_laboratory_sciences', 'ucf', 'Blood Bank Technologist'),
  ('ucf_biomedical_sciences', 'ucf', 'Clinical Research Coordinator'),
  ('ucf_biomedical_sciences', 'ucf', 'Medical Sales Representative'),
  ('ucf_biomedical_sciences', 'ucf', 'Biological Technician'),
  ('ucf_biomedical_sciences', 'ucf', 'Research Assistant'),
  ('ucf_communication_sciences_and_disorders', 'ucf', 'Speech-Language Pathology Assistant'),
  ('ucf_communication_sciences_and_disorders', 'ucf', 'Audiology Assistant'),
  ('ucf_communication_sciences_and_disorders', 'ucf', 'Early Intervention Specialist'),
  ('ucf_communication_sciences_and_disorders', 'ucf', 'Rehabilitation Aide'),
  ('ucf_digital_media_and_game_design', 'ucf', 'Game QA Tester'),
  ('ucf_digital_media_and_game_design', 'ucf', 'Junior 3D Artist'),
  ('ucf_digital_media_and_game_design', 'ucf', 'UX Designer'),
  ('ucf_digital_media_and_game_design', 'ucf', 'Junior Game Designer'),
  ('ucf_emerging_media_character_animation', 'ucf', '3D Generalist'),
  ('ucf_emerging_media_character_animation', 'ucf', 'Motion Graphics Artist'),
  ('ucf_emerging_media_character_animation', 'ucf', 'Character Animator'),
  ('ucf_emerging_media_character_animation', 'ucf', 'Visualization Artist'),
  ('ucf_psychology', 'ucf', 'Case Manager'),
  ('ucf_psychology', 'ucf', 'Human Resources Assistant'),
  ('ucf_psychology', 'ucf', 'Registered Behavior Technician'),
  ('ucf_psychology', 'ucf', 'Mental Health Technician'),
  ('ucf_sociology', 'ucf', 'Case Manager'),
  ('ucf_sociology', 'ucf', 'Community Outreach Coordinator'),
  ('ucf_sociology', 'ucf', 'Research Assistant'),
  ('ucf_sociology', 'ucf', 'Social Services Specialist'),
  ('ucf_history', 'ucf', 'Field Technician (CRM)'),
  ('ucf_history', 'ucf', 'Grant Writer'),
  ('ucf_history', 'ucf', 'Museum Assistant'),
  ('ucf_history', 'ucf', 'Compliance Analyst'),
  ('ucf_anthropology', 'ucf', 'Field Technician (CRM)'),
  ('ucf_anthropology', 'ucf', 'Cultural Resource Specialist'),
  ('ucf_anthropology', 'ucf', 'Research Assistant'),
  ('ucf_anthropology', 'ucf', 'Museum Technician'),
  ('ucf_political_science', 'ucf', 'Legislative Aide'),
  ('ucf_political_science', 'ucf', 'Field Organizer'),
  ('ucf_political_science', 'ucf', 'Policy Analyst (Junior)'),
  ('ucf_political_science', 'ucf', 'Campaign Coordinator'),
  ('ucf_social_work', 'ucf', 'Child Protective Investigator'),
  ('ucf_social_work', 'ucf', 'Family Support Worker'),
  ('ucf_social_work', 'ucf', 'Social Services Coordinator'),
  ('ucf_social_work', 'ucf', 'Case Manager'),
  ('valencia_computing_technology_software_development', 'valencia', 'Software Developer I'),
  ('valencia_computing_technology_software_development', 'valencia', 'Cloud Support Associate'),
  ('valencia_computing_technology_software_development', 'valencia', 'Applications Analyst'),
  ('valencia_computing_technology_software_development', 'valencia', 'Junior DevOps Engineer'),
  ('valencia_computer_information_technology', 'valencia', 'IT Support Specialist'),
  ('valencia_computer_information_technology', 'valencia', 'Junior Network Administrator'),
  ('valencia_computer_information_technology', 'valencia', 'System Administrator I'),
  ('valencia_computer_information_technology', 'valencia', 'Technical Support Analyst'),
  ('valencia_computer_programming_analysis', 'valencia', 'Junior Programmer'),
  ('valencia_computer_programming_analysis', 'valencia', 'Front-End Developer'),
  ('valencia_computer_programming_analysis', 'valencia', 'QA Tester'),
  ('valencia_computer_programming_analysis', 'valencia', 'Database Assistant'),
  ('valencia_network_engineering_technology', 'valencia', 'Network Technician'),
  ('valencia_network_engineering_technology', 'valencia', 'NOC Technician'),
  ('valencia_network_engineering_technology', 'valencia', 'Junior Network Engineer'),
  ('valencia_network_engineering_technology', 'valencia', 'Telecommunications Specialist'),
  ('valencia_cyber_security', 'valencia', 'SOC Analyst (Tier 1)'),
  ('valencia_cyber_security', 'valencia', 'InfoSec Assistant'),
  ('valencia_cyber_security', 'valencia', 'IAM Specialist'),
  ('valencia_database_administration', 'valencia', 'Junior DBA'),
  ('valencia_database_administration', 'valencia', 'Data Entry Specialist'),
  ('valencia_database_administration', 'valencia', 'SQL Technician'),
  ('valencia_it_support_specialist', 'valencia', 'Help Desk Technician'),
  ('valencia_it_support_specialist', 'valencia', 'Desktop Support'),
  ('valencia_it_support_specialist', 'valencia', 'Deployment Tech'),
  ('valencia_network_support_technician', 'valencia', 'Junior Network Associate'),
  ('valencia_network_support_technician', 'valencia', 'Cable Installer'),
  ('valencia_network_support_technician', 'valencia', 'Field Tech'),
  ('valencia_web_development', 'valencia', 'Junior Web Designer'),
  ('valencia_web_development', 'valencia', 'Front-End Coder'),
  ('valencia_web_development', 'valencia', 'WordPress Admin'),
  ('valencia_electrical_computer_engineering_technology', 'valencia', 'Electrical Engineering Technologist'),
  ('valencia_electrical_computer_engineering_technology', 'valencia', 'Semiconductor Process Tech'),
  ('valencia_electrical_computer_engineering_technology', 'valencia', 'Photonics Specialist'),
  ('valencia_electrical_computer_engineering_technology', 'valencia', 'Control Systems Integrator'),
  ('valencia_electrical_engineering_technology', 'valencia', 'Electronics Technician'),
  ('valencia_electrical_engineering_technology', 'valencia', 'Field Service Technician'),
  ('valencia_electrical_engineering_technology', 'valencia', 'Test Technician'),
  ('valencia_electrical_engineering_technology', 'valencia', 'Assembly Technician'),
  ('valencia_engineering_technology', 'valencia', 'Manufacturing Technician'),
  ('valencia_engineering_technology', 'valencia', 'Quality Assurance Tech'),
  ('valencia_engineering_technology', 'valencia', 'CAD Drafter'),
  ('valencia_engineering_technology', 'valencia', 'Industrial Engineering Tech'),
  ('valencia_automotive_service_technology', 'valencia', 'Automotive Technician'),
  ('valencia_automotive_service_technology', 'valencia', 'Lube Technician'),
  ('valencia_automotive_service_technology', 'valencia', 'Service Advisor'),
  ('valencia_electrician', 'valencia', 'Electrician Apprentice'),
  ('valencia_electrician', 'valencia', 'Wireman Helper'),
  ('valencia_electrician', 'valencia', 'Maintenance Helper'),
  ('valencia_hvacr_technician', 'valencia', 'HVAC Installer'),
  ('valencia_hvacr_technician', 'valencia', 'HVAC Service Tech'),
  ('valencia_hvacr_technician', 'valencia', 'Refrigeration Tech'),
  ('valencia_welding_technology', 'valencia', 'Welder (MIG/TIG/Stick)'),
  ('valencia_welding_technology', 'valencia', 'Structural Fabricator'),
  ('valencia_welding_technology', 'valencia', 'Welder Helper'),
  ('valencia_nursing', 'valencia', 'Nurse Manager (Unit)'),
  ('valencia_nursing', 'valencia', 'Clinical Nurse Leader'),
  ('valencia_nursing', 'valencia', 'Public Health Nurse'),
  ('valencia_nursing', 'valencia', 'Nurse Educator (Adjunct)'),
  ('valencia_health_services_administration', 'valencia', 'Practice Manager'),
  ('valencia_health_services_administration', 'valencia', 'Health Services Manager'),
  ('valencia_health_services_administration', 'valencia', 'Patient Access Director'),
  ('valencia_health_services_administration', 'valencia', 'Compliance Coordinator'),
  ('valencia_nursing', 'valencia', 'Registered Nurse (RN)'),
  ('valencia_nursing', 'valencia', 'Emergency Room Nurse'),
  ('valencia_nursing', 'valencia', 'ICU Nurse'),
  ('valencia_nursing', 'valencia', 'Home Health Nurse'),
  ('valencia_diagnostic_medical_sonography', 'valencia', 'Diagnostic Sonographer'),
  ('valencia_diagnostic_medical_sonography', 'valencia', 'Vascular Technologist'),
  ('valencia_diagnostic_medical_sonography', 'valencia', 'Ultrasound Tech'),
  ('valencia_dental_hygiene', 'valencia', 'Dental Hygienist'),
  ('valencia_dental_hygiene', 'valencia', 'Public Health Hygienist'),
  ('valencia_health_information_technology', 'valencia', 'Health Info Technician'),
  ('valencia_health_information_technology', 'valencia', 'Medical Coder'),
  ('valencia_health_information_technology', 'valencia', 'Revenue Cycle Analyst'),
  ('valencia_radiography', 'valencia', 'Radiologic Technologist'),
  ('valencia_radiography', 'valencia', 'CT Technologist'),
  ('valencia_radiography', 'valencia', 'MRI Technologist'),
  ('valencia_respiratory_care', 'valencia', 'Respiratory Therapist'),
  ('valencia_respiratory_care', 'valencia', 'Pulmonary Function Tech'),
  ('valencia_respiratory_care', 'valencia', 'Neonatal/Pediatric RT'),
  ('valencia_physical_therapist_assistant', 'valencia', 'Physical Therapist Assistant'),
  ('valencia_physical_therapist_assistant', 'valencia', 'Home Health PTA'),
  ('valencia_physical_therapist_assistant', 'valencia', 'Rehab Technician'),
  ('valencia_emergency_medical_services', 'valencia', 'Paramedic'),
  ('valencia_emergency_medical_services', 'valencia', 'ER Technician'),
  ('valencia_emergency_medical_services', 'valencia', 'EMS Supervisor'),
  ('valencia_medical_billing_and_coding', 'valencia', 'Medical Biller'),
  ('valencia_medical_billing_and_coding', 'valencia', 'Medical Coder (Entry)'),
  ('valencia_medical_billing_and_coding', 'valencia', 'Billing Specialist'),
  ('valencia_medical_office_administration', 'valencia', 'Medical Receptionist'),
  ('valencia_medical_office_administration', 'valencia', 'Patient Coordinator'),
  ('valencia_medical_office_administration', 'valencia', 'Unit Secretary'),
  ('valencia_phlebotomy', 'valencia', 'Phlebotomist'),
  ('valencia_phlebotomy', 'valencia', 'Lab Assistant'),
  ('valencia_practical_nursing', 'valencia', 'Licensed Practical Nurse'),
  ('valencia_practical_nursing', 'valencia', 'Clinic Nurse'),
  ('valencia_practical_nursing', 'valencia', 'Home Health LPN'),
  ('valencia_business_organizational_leadership', 'valencia', 'Operations Manager'),
  ('valencia_business_organizational_leadership', 'valencia', 'HR Generalist'),
  ('valencia_business_organizational_leadership', 'valencia', 'Project Manager (Entry)'),
  ('valencia_business_organizational_leadership', 'valencia', 'Sales Manager'),
  ('valencia_accounting_technology', 'valencia', 'Bookkeeper'),
  ('valencia_accounting_technology', 'valencia', 'Accounts Payable Clerk'),
  ('valencia_accounting_technology', 'valencia', 'Payroll Coordinator'),
  ('valencia_accounting_technology', 'valencia', 'Tax Preparer'),
  ('valencia_business_administration', 'valencia', 'Assistant Manager'),
  ('valencia_business_administration', 'valencia', 'Customer Service Manager'),
  ('valencia_business_administration', 'valencia', 'Admin Services Manager'),
  ('valencia_business_administration', 'valencia', 'Sales Representative'),
  ('valencia_office_administration', 'valencia', 'Executive Assistant'),
  ('valencia_office_administration', 'valencia', 'Office Manager'),
  ('valencia_office_administration', 'valencia', 'Admin Coordinator'),
  ('valencia_public_safety_administration', 'valencia', 'Fire Battalion Chief'),
  ('valencia_public_safety_administration', 'valencia', 'Police Lieutenant'),
  ('valencia_public_safety_administration', 'valencia', 'Emergency Management Director'),
  ('valencia_public_safety_administration', 'valencia', 'Public Safety Director'),
  ('valencia_fire_science_technology', 'valencia', 'Firefighter (Career)'),
  ('valencia_fire_science_technology', 'valencia', 'Fire Inspector'),
  ('valencia_fire_science_technology', 'valencia', 'Fire Investigator'),
  ('valencia_paralegal_studies', 'valencia', 'Paralegal'),
  ('valencia_paralegal_studies', 'valencia', 'Legal Assistant'),
  ('valencia_paralegal_studies', 'valencia', 'Compliance Specialist'),
  ('valencia_legal_assisting', 'valencia', 'Legal Assistant'),
  ('valencia_legal_assisting', 'valencia', 'Court Clerk'),
  ('valencia_emergency_medical_technician', 'valencia', 'EMT-Basic'),
  ('valencia_emergency_medical_technician', 'valencia', 'ER Tech'),
  ('valencia_fire_fighter', 'valencia', 'Firefighter'),
  ('valencia_culinary_management', 'valencia', 'Sous Chef'),
  ('valencia_culinary_management', 'valencia', 'Kitchen Manager'),
  ('valencia_culinary_management', 'valencia', 'Catering Manager'),
  ('valencia_hospitality_tourism_management', 'valencia', 'Front Office Manager'),
  ('valencia_hospitality_tourism_management', 'valencia', 'Guest Services Manager'),
  ('valencia_hospitality_tourism_management', 'valencia', 'Event Coordinator'),
  ('valencia_film_production_technology', 'valencia', 'Production Assistant'),
  ('valencia_film_production_technology', 'valencia', 'Camera Operator'),
  ('valencia_film_production_technology', 'valencia', 'Video Editor'),
  ('valencia_film_production_technology', 'valencia', 'Grip/Electric'),
  ('valencia_graphic_design_technology', 'valencia', 'Junior Designer'),
  ('valencia_graphic_design_technology', 'valencia', 'Web Designer'),
  ('valencia_graphic_design_technology', 'valencia', 'Production Artist'),
  ('valencia_interior_design', 'valencia', 'Junior Designer'),
  ('valencia_interior_design', 'valencia', 'Kitchen Designer'),
  ('valencia_interior_design', 'valencia', 'Showroom Consultant'),
  ('valencia_culinary_arts', 'valencia', 'Line Cook'),
  ('valencia_culinary_arts', 'valencia', 'Prep Cook'),
  ('valencia_digital_mediamultimedia', 'valencia', 'Content Creator'),
  ('valencia_digital_mediamultimedia', 'valencia', 'Multimedia Specialist'),
  ('valencia_digital_mediamultimedia', 'valencia', 'Junior Graphic Artist'),
  ('valencia_early_childhood_education', 'valencia', 'Preschool Teacher'),
  ('valencia_early_childhood_education', 'valencia', 'Center Director'),
  ('valencia_early_childhood_education', 'valencia', 'Teacher Assistant'),
  ('valencia_early_childhood_education', 'valencia', 'Childcare Worker'),
  ('valencia_human_services', 'valencia', 'Case Management Aide'),
  ('valencia_human_services', 'valencia', 'Outreach Worker'),
  ('valencia_human_services', 'valencia', 'Social Services Assistant')
) AS links(program_key, school, career_title)
JOIN career_paths cp ON cp.title = links.career_title
ON CONFLICT (program_key, school, career_path_id) DO NOTHING;

