-- Insert program to skill mappings (911 links)
INSERT INTO program_skills (program_key, school, skill_id)
SELECT links.program_key, links.school, sk.id
FROM (VALUES
  ('fullsail_game_development', 'fullsail', 'C++'),
  ('fullsail_game_development', 'fullsail', 'C#'),
  ('fullsail_game_development', 'fullsail', 'Data Structures and Algorithms'),
  ('fullsail_game_development', 'fullsail', 'Linear Algebra'),
  ('fullsail_game_development', 'fullsail', 'Engine Architecture'),
  ('fullsail_game_development', 'fullsail', 'Artificial Intelligence'),
  ('fullsail_game_development', 'fullsail', 'Unity'),
  ('fullsail_game_development', 'fullsail', 'Unreal Engine'),
  ('fullsail_game_development', 'fullsail', 'Problem Solving'),
  ('fullsail_game_design', 'fullsail', 'Game Mechanics Design'),
  ('fullsail_game_design', 'fullsail', 'Systems Balancing'),
  ('fullsail_game_design', 'fullsail', 'Level Design'),
  ('fullsail_game_design', 'fullsail', 'Psychology of Play'),
  ('fullsail_game_design', 'fullsail', 'Unity'),
  ('fullsail_game_design', 'fullsail', 'Unreal Engine'),
  ('fullsail_game_design', 'fullsail', 'Critical Thinking'),
  ('fullsail_game_design', 'fullsail', 'Player Empathy'),
  ('fullsail_game_art', 'fullsail', '3D Modeling'),
  ('fullsail_game_art', 'fullsail', 'Texturing'),
  ('fullsail_game_art', 'fullsail', 'PBR Workflows'),
  ('fullsail_game_art', 'fullsail', 'Rigging'),
  ('fullsail_game_art', 'fullsail', 'Game Animation'),
  ('fullsail_game_art', 'fullsail', 'Maya'),
  ('fullsail_game_art', 'fullsail', 'ZBrush'),
  ('fullsail_game_art', 'fullsail', 'Adobe Substance Painter'),
  ('fullsail_game_art', 'fullsail', 'Attention to Detail'),
  ('fullsail_game_business_esports', 'fullsail', 'Esports Management'),
  ('fullsail_game_business_esports', 'fullsail', 'Game Business Models'),
  ('fullsail_game_business_esports', 'fullsail', 'Player Contracts'),
  ('fullsail_game_business_esports', 'fullsail', 'Social Media Management'),
  ('fullsail_game_business_esports', 'fullsail', 'Communication'),
  ('fullsail_game_business_esports', 'fullsail', 'Leadership'),
  ('fullsail_game_business_esports', 'fullsail', 'Conflict Resolution'),
  ('fullsail_computer_science', 'fullsail', 'Software Development Lifecycle'),
  ('fullsail_computer_science', 'fullsail', 'Machine Learning'),
  ('fullsail_computer_science', 'fullsail', 'Deep Learning'),
  ('fullsail_computer_science', 'fullsail', 'Swift'),
  ('fullsail_computer_science', 'fullsail', 'Kotlin'),
  ('fullsail_computer_science', 'fullsail', 'Git'),
  ('fullsail_computer_science', 'fullsail', 'Agile Methodologies'),
  ('fullsail_computer_science', 'fullsail', 'Problem Solving'),
  ('fullsail_computer_science', 'fullsail', 'Analytical Thinking'),
  ('fullsail_cybersecurity', 'fullsail', 'Threat Intelligence'),
  ('fullsail_cybersecurity', 'fullsail', 'Incident Response'),
  ('fullsail_cybersecurity', 'fullsail', 'Network Security'),
  ('fullsail_cybersecurity', 'fullsail', 'CompTIA Security+'),
  ('fullsail_cybersecurity', 'fullsail', 'CompTIA CySA+'),
  ('fullsail_cybersecurity', 'fullsail', 'Virtual Sandbox Environments'),
  ('fullsail_cybersecurity', 'fullsail', 'Critical Thinking'),
  ('fullsail_cybersecurity', 'fullsail', 'Attention to Detail'),
  ('fullsail_information_technology', 'fullsail', 'Cloud Networking'),
  ('fullsail_information_technology', 'fullsail', 'Virtualization Technologies'),
  ('fullsail_information_technology', 'fullsail', 'Systems Administration'),
  ('fullsail_information_technology', 'fullsail', 'Scripting'),
  ('fullsail_information_technology', 'fullsail', 'AWS'),
  ('fullsail_information_technology', 'fullsail', 'Azure'),
  ('fullsail_information_technology', 'fullsail', 'Troubleshooting'),
  ('fullsail_information_technology', 'fullsail', 'Communication'),
  ('fullsail_web_development', 'fullsail', 'HTML'),
  ('fullsail_web_development', 'fullsail', 'CSS'),
  ('fullsail_web_development', 'fullsail', 'JavaScript'),
  ('fullsail_web_development', 'fullsail', 'React'),
  ('fullsail_web_development', 'fullsail', 'Node.js'),
  ('fullsail_web_development', 'fullsail', 'SQL'),
  ('fullsail_web_development', 'fullsail', 'NoSQL'),
  ('fullsail_web_development', 'fullsail', 'Cloud Application Deployment'),
  ('fullsail_web_development', 'fullsail', 'Problem Solving'),
  ('fullsail_user_experience', 'fullsail', 'UX Research'),
  ('fullsail_user_experience', 'fullsail', 'Human-Centered Design'),
  ('fullsail_user_experience', 'fullsail', 'Psychology of Perception'),
  ('fullsail_user_experience', 'fullsail', 'Wireframing'),
  ('fullsail_user_experience', 'fullsail', 'Prototyping'),
  ('fullsail_user_experience', 'fullsail', 'Figma'),
  ('fullsail_user_experience', 'fullsail', 'Adobe XD'),
  ('fullsail_user_experience', 'fullsail', 'User Testing'),
  ('fullsail_user_experience', 'fullsail', 'Empathy'),
  ('fullsail_user_experience', 'fullsail', 'Communication'),
  ('fullsail_computer_animation', 'fullsail', 'Storyboarding'),
  ('fullsail_computer_animation', 'fullsail', '3D Modeling'),
  ('fullsail_computer_animation', 'fullsail', 'Rigging'),
  ('fullsail_computer_animation', 'fullsail', 'Animation'),
  ('fullsail_computer_animation', 'fullsail', 'Compositing'),
  ('fullsail_computer_animation', 'fullsail', 'Adobe Creative Cloud'),
  ('fullsail_computer_animation', 'fullsail', 'Maxon One'),
  ('fullsail_computer_animation', 'fullsail', 'Nuke'),
  ('fullsail_computer_animation', 'fullsail', 'Creativity'),
  ('fullsail_computer_animation', 'fullsail', 'Attention to Detail'),
  ('fullsail_digital_arts_design', 'fullsail', 'Motion Graphics'),
  ('fullsail_digital_arts_design', 'fullsail', '3D for Motion Design'),
  ('fullsail_digital_arts_design', 'fullsail', 'Live Event Design'),
  ('fullsail_digital_arts_design', 'fullsail', 'Projection Mapping'),
  ('fullsail_digital_arts_design', 'fullsail', 'After Effects'),
  ('fullsail_digital_arts_design', 'fullsail', 'Cinema 4D'),
  ('fullsail_digital_arts_design', 'fullsail', 'Creativity'),
  ('fullsail_digital_arts_design', 'fullsail', 'Time Management'),
  ('fullsail_graphic_design', 'fullsail', 'Branding & Identity'),
  ('fullsail_graphic_design', 'fullsail', 'Logo Design'),
  ('fullsail_graphic_design', 'fullsail', 'Typography'),
  ('fullsail_graphic_design', 'fullsail', 'Print Design'),
  ('fullsail_graphic_design', 'fullsail', 'Packaging Design'),
  ('fullsail_graphic_design', 'fullsail', 'Digital Publishing'),
  ('fullsail_graphic_design', 'fullsail', 'Adobe Creative Suite'),
  ('fullsail_graphic_design', 'fullsail', 'Creativity'),
  ('fullsail_graphic_design', 'fullsail', 'Attention to Detail'),
  ('fullsail_film', 'fullsail', 'Set Operations'),
  ('fullsail_film', 'fullsail', 'Lighting'),
  ('fullsail_film', 'fullsail', 'Camera Operation'),
  ('fullsail_film', 'fullsail', 'Video Editing'),
  ('fullsail_film', 'fullsail', 'Visual Effects'),
  ('fullsail_film', 'fullsail', '4K Digital Cinema Cameras'),
  ('fullsail_film', 'fullsail', 'Teamwork'),
  ('fullsail_film', 'fullsail', 'Adaptability'),
  ('fullsail_digital_cinematography', 'fullsail', 'Electronic Field Production'),
  ('fullsail_digital_cinematography', 'fullsail', 'Documentary Shooting'),
  ('fullsail_digital_cinematography', 'fullsail', 'Data Management'),
  ('fullsail_digital_cinematography', 'fullsail', 'Solo Production'),
  ('fullsail_digital_cinematography', 'fullsail', 'Digital Workflow'),
  ('fullsail_digital_cinematography', 'fullsail', 'Self-Direction'),
  ('fullsail_digital_cinematography', 'fullsail', 'Time Management'),
  ('fullsail_creative_writing', 'fullsail', 'Scriptwriting'),
  ('fullsail_creative_writing', 'fullsail', 'Television Writing'),
  ('fullsail_creative_writing', 'fullsail', 'Transmedia Writing'),
  ('fullsail_creative_writing', 'fullsail', 'Writing for Games'),
  ('fullsail_creative_writing', 'fullsail', 'Storytelling'),
  ('fullsail_creative_writing', 'fullsail', 'Creativity'),
  ('fullsail_creative_writing', 'fullsail', 'Research'),
  ('fullsail_media_communications', 'fullsail', 'Multimedia Storytelling'),
  ('fullsail_media_communications', 'fullsail', 'Media Research'),
  ('fullsail_media_communications', 'fullsail', 'Media Sociology'),
  ('fullsail_media_communications', 'fullsail', 'Integrated Media Campaigns'),
  ('fullsail_media_communications', 'fullsail', 'Communication'),
  ('fullsail_media_communications', 'fullsail', 'Strategic Thinking'),
  ('fullsail_media_communications', 'fullsail', 'Audience Analysis'),
  ('fullsail_sportscasting', 'fullsail', 'Vocal Training'),
  ('fullsail_sportscasting', 'fullsail', 'On-Camera Delivery'),
  ('fullsail_sportscasting', 'fullsail', 'Sports Digital Production'),
  ('fullsail_sportscasting', 'fullsail', 'Video Editing'),
  ('fullsail_sportscasting', 'fullsail', 'Public Speaking'),
  ('fullsail_sportscasting', 'fullsail', 'Composure Under Pressure'),
  ('fullsail_sportscasting', 'fullsail', 'Sports Knowledge'),
  ('fullsail_recording_arts', 'fullsail', 'Studio Engineering'),
  ('fullsail_recording_arts', 'fullsail', 'Signal Flow'),
  ('fullsail_recording_arts', 'fullsail', 'Mixing Techniques'),
  ('fullsail_recording_arts', 'fullsail', 'Audio Post-Production'),
  ('fullsail_recording_arts', 'fullsail', 'Sound Design'),
  ('fullsail_recording_arts', 'fullsail', 'Foley'),
  ('fullsail_recording_arts', 'fullsail', 'Large-Format Consoles'),
  ('fullsail_recording_arts', 'fullsail', 'Pro Tools'),
  ('fullsail_recording_arts', 'fullsail', 'Active Listening'),
  ('fullsail_recording_arts', 'fullsail', 'Attention to Detail'),
  ('fullsail_audio_production', 'fullsail', 'Project Studio Workflow'),
  ('fullsail_audio_production', 'fullsail', 'Game Audio Production'),
  ('fullsail_audio_production', 'fullsail', 'Adaptive Music Implementation'),
  ('fullsail_audio_production', 'fullsail', 'Digital Audio Workstation'),
  ('fullsail_audio_production', 'fullsail', 'Audio Interface'),
  ('fullsail_audio_production', 'fullsail', 'Self-Direction'),
  ('fullsail_audio_production', 'fullsail', 'Client Communication'),
  ('fullsail_music_production', 'fullsail', 'Music Composition'),
  ('fullsail_music_production', 'fullsail', 'Musical Structure and Analysis'),
  ('fullsail_music_production', 'fullsail', 'Songwriting'),
  ('fullsail_music_production', 'fullsail', 'Musical Arrangement'),
  ('fullsail_music_production', 'fullsail', 'Instrumentation'),
  ('fullsail_music_production', 'fullsail', 'Orchestration'),
  ('fullsail_music_production', 'fullsail', 'DAW Software'),
  ('fullsail_music_production', 'fullsail', 'Creativity'),
  ('fullsail_music_production', 'fullsail', 'Collaboration'),
  ('fullsail_show_production', 'fullsail', 'Live Sound Systems'),
  ('fullsail_show_production', 'fullsail', 'Intelligent Lighting Programming'),
  ('fullsail_show_production', 'fullsail', 'Video Wall Management'),
  ('fullsail_show_production', 'fullsail', 'Power Distribution'),
  ('fullsail_show_production', 'fullsail', 'Stage Management'),
  ('fullsail_show_production', 'fullsail', 'Line Array Systems'),
  ('fullsail_show_production', 'fullsail', 'Lighting Consoles'),
  ('fullsail_show_production', 'fullsail', 'Problem Solving'),
  ('fullsail_show_production', 'fullsail', 'Teamwork'),
  ('fullsail_entertainment_business', 'fullsail', 'Business Law'),
  ('fullsail_entertainment_business', 'fullsail', 'Finance'),
  ('fullsail_entertainment_business', 'fullsail', 'Management'),
  ('fullsail_entertainment_business', 'fullsail', 'Entertainment Business Models'),
  ('fullsail_entertainment_business', 'fullsail', 'Organizational Skills'),
  ('fullsail_entertainment_business', 'fullsail', 'Communication'),
  ('fullsail_entertainment_business', 'fullsail', 'Networking'),
  ('fullsail_music_business', 'fullsail', 'Artist Management'),
  ('fullsail_music_business', 'fullsail', 'Music Copyright'),
  ('fullsail_music_business', 'fullsail', 'Music Publishing'),
  ('fullsail_music_business', 'fullsail', 'Contract Negotiation'),
  ('fullsail_music_business', 'fullsail', 'Streaming Revenue Models'),
  ('fullsail_music_business', 'fullsail', 'Networking'),
  ('fullsail_music_business', 'fullsail', 'Negotiation'),
  ('fullsail_music_business', 'fullsail', 'Relationship Building'),
  ('fullsail_digital_marketing', 'fullsail', 'Digital Analytics'),
  ('fullsail_digital_marketing', 'fullsail', 'Search Engine Optimization'),
  ('fullsail_digital_marketing', 'fullsail', 'Social Media Marketing'),
  ('fullsail_digital_marketing', 'fullsail', 'Campaign Management'),
  ('fullsail_digital_marketing', 'fullsail', 'Google Analytics'),
  ('fullsail_digital_marketing', 'fullsail', 'SEMrush'),
  ('fullsail_digital_marketing', 'fullsail', 'Analytical Thinking'),
  ('fullsail_digital_marketing', 'fullsail', 'Creativity'),
  ('fullsail_digital_marketing', 'fullsail', 'Communication'),
  ('fullsail_sports_marketing_media', 'fullsail', 'Fan Engagement'),
  ('fullsail_sports_marketing_media', 'fullsail', 'Social Media Methods'),
  ('fullsail_sports_marketing_media', 'fullsail', 'Sports Sales'),
  ('fullsail_sports_marketing_media', 'fullsail', 'Sponsorship Management'),
  ('fullsail_sports_marketing_media', 'fullsail', 'Community Building'),
  ('fullsail_sports_marketing_media', 'fullsail', 'Sales Skills'),
  ('fullsail_sports_marketing_media', 'fullsail', 'Enthusiasm'),
  ('orange_heating_ventilation_airconditioningrefrigeration_1', 'orange', 'EPA Section 608 Certification'),
  ('orange_heating_ventilation_airconditioningrefrigeration_1', 'orange', 'Thermodynamics'),
  ('orange_heating_ventilation_airconditioningrefrigeration_1', 'orange', 'Soldering and Brazing'),
  ('orange_heating_ventilation_airconditioningrefrigeration_1', 'orange', 'Electrical Troubleshooting'),
  ('orange_heating_ventilation_airconditioningrefrigeration_1', 'orange', 'Refrigerant Handling'),
  ('orange_heating_ventilation_airconditioningrefrigeration_1', 'orange', 'Schematic Reading'),
  ('orange_heating_ventilation_airconditioningrefrigeration_2', 'orange', 'HVAC Excellence Certification'),
  ('orange_heating_ventilation_airconditioningrefrigeration_2', 'orange', 'Psychrometrics'),
  ('orange_heating_ventilation_airconditioningrefrigeration_2', 'orange', 'Light Commercial Refrigeration'),
  ('orange_heating_ventilation_airconditioningrefrigeration_2', 'orange', 'Heat Pump Systems'),
  ('orange_heating_ventilation_airconditioningrefrigeration_2', 'orange', 'Humidity Control'),
  ('orange_heating_ventilation_airconditioningrefrigeration_2', 'orange', 'Complex Diagnostics'),
  ('orange_electricity', 'orange', 'NCCER Electrical Level 1 & 2'),
  ('orange_electricity', 'orange', 'National Electrical Code (NEC)'),
  ('orange_electricity', 'orange', 'Conduit Bending'),
  ('orange_electricity', 'orange', 'Three-Phase Power Systems'),
  ('orange_electricity', 'orange', 'OSHA Safety Standards'),
  ('orange_electricity', 'orange', 'Blueprint Reading'),
  ('orange_welding_technology', 'orange', 'AWS Certification'),
  ('orange_welding_technology', 'orange', 'SMAW (Stick Welding)'),
  ('orange_welding_technology', 'orange', 'GMAW (MIG Welding)'),
  ('orange_welding_technology', 'orange', 'GTAW (TIG Welding)'),
  ('orange_welding_technology', 'orange', 'Blueprint Reading'),
  ('orange_welding_technology', 'orange', 'Thermal Cutting'),
  ('orange_computeraided_drawing_and_modeling', 'orange', 'AutoCAD'),
  ('orange_computeraided_drawing_and_modeling', 'orange', 'Revit'),
  ('orange_computeraided_drawing_and_modeling', 'orange', 'Autodesk Certified User'),
  ('orange_computeraided_drawing_and_modeling', 'orange', 'Building Information Modeling (BIM)'),
  ('orange_computeraided_drawing_and_modeling', 'orange', '2D/3D Drafting'),
  ('orange_computeraided_drawing_and_modeling', 'orange', 'Technical Drawing'),
  ('orange_building_construction_technologies', 'orange', 'OSHA 10 Certification'),
  ('orange_building_construction_technologies', 'orange', 'NCCER Core'),
  ('orange_building_construction_technologies', 'orange', 'Blueprint Reading'),
  ('orange_building_construction_technologies', 'orange', 'Carpentry'),
  ('orange_building_construction_technologies', 'orange', 'Masonry'),
  ('orange_building_construction_technologies', 'orange', 'Site Layout'),
  ('orange_diesel_systems_technician', 'orange', 'ASE Medium-Heavy Truck Certification'),
  ('orange_diesel_systems_technician', 'orange', 'Diesel Engine Overhaul'),
  ('orange_diesel_systems_technician', 'orange', 'Air Brake Systems'),
  ('orange_diesel_systems_technician', 'orange', 'Hydraulic Systems'),
  ('orange_diesel_systems_technician', 'orange', 'Emissions Control Systems'),
  ('orange_diesel_systems_technician', 'orange', 'Electronic Diagnostics'),
  ('orange_master_automotive_service_technology_1', 'orange', 'ASE A1 (Engine Repair)'),
  ('orange_master_automotive_service_technology_1', 'orange', 'ASE A4 (Suspension/Steering)'),
  ('orange_master_automotive_service_technology_1', 'orange', 'ASE A5 (Brakes)'),
  ('orange_master_automotive_service_technology_1', 'orange', 'ASE A6 (Electrical)'),
  ('orange_master_automotive_service_technology_1', 'orange', 'NATEF Standards'),
  ('orange_master_automotive_service_technology_1', 'orange', 'Under-Car Systems'),
  ('orange_master_automotive_service_technology_2', 'orange', 'ASE A2 (Automatic Transmission)'),
  ('orange_master_automotive_service_technology_2', 'orange', 'ASE A3 (Manual Drivetrain)'),
  ('orange_master_automotive_service_technology_2', 'orange', 'ASE A7 (HVAC)'),
  ('orange_master_automotive_service_technology_2', 'orange', 'ASE A8 (Engine Performance)'),
  ('orange_master_automotive_service_technology_2', 'orange', 'Advanced Diagnostics'),
  ('orange_master_automotive_service_technology_2', 'orange', 'Drivability Troubleshooting'),
  ('orange_automotive_collision_technology_technician', 'orange', 'I-CAR Certification'),
  ('orange_automotive_collision_technology_technician', 'orange', 'ASE Collision Repair'),
  ('orange_automotive_collision_technology_technician', 'orange', 'Frame Straightening'),
  ('orange_automotive_collision_technology_technician', 'orange', 'Paint Application'),
  ('orange_automotive_collision_technology_technician', 'orange', 'Damage Analysis'),
  ('orange_automotive_collision_technology_technician', 'orange', 'Panel Repair'),
  ('orange_commercial_vehicle_driving', 'orange', 'CDL Class A'),
  ('orange_commercial_vehicle_driving', 'orange', 'ELDT Compliance'),
  ('orange_commercial_vehicle_driving', 'orange', 'Vehicle Inspection'),
  ('orange_commercial_vehicle_driving', 'orange', 'Backing Maneuvers'),
  ('orange_commercial_vehicle_driving', 'orange', 'DOT Regulations'),
  ('orange_commercial_vehicle_driving', 'orange', 'Defensive Driving'),
  ('orange_medical_assisting', 'orange', 'CMA/RMA Certification'),
  ('orange_medical_assisting', 'orange', 'Phlebotomy'),
  ('orange_medical_assisting', 'orange', 'EKG Administration'),
  ('orange_medical_assisting', 'orange', 'Medical Coding'),
  ('orange_medical_assisting', 'orange', 'Pharmacology'),
  ('orange_medical_assisting', 'orange', 'Patient Care'),
  ('orange_dental_assisting_technology_and_management', 'orange', 'Florida Expanded Functions Certificate'),
  ('orange_dental_assisting_technology_and_management', 'orange', 'CDA Certification'),
  ('orange_dental_assisting_technology_and_management', 'orange', 'Dental Radiography'),
  ('orange_dental_assisting_technology_and_management', 'orange', 'Chairside Assisting'),
  ('orange_dental_assisting_technology_and_management', 'orange', 'Infection Control'),
  ('orange_dental_assisting_technology_and_management', 'orange', 'Patient Communication'),
  ('orange_surgical_technology', 'orange', 'CST Certification'),
  ('orange_surgical_technology', 'orange', 'Sterile Field Maintenance'),
  ('orange_surgical_technology', 'orange', 'Surgical Instrumentation'),
  ('orange_surgical_technology', 'orange', 'Anatomy and Physiology'),
  ('orange_surgical_technology', 'orange', 'Surgical Procedures'),
  ('orange_surgical_technology', 'orange', 'Attention to Detail'),
  ('orange_pharmacy_technician', 'orange', 'CPhT Certification'),
  ('orange_pharmacy_technician', 'orange', 'Sterile Compounding'),
  ('orange_pharmacy_technician', 'orange', 'Medication Chemistry'),
  ('orange_pharmacy_technician', 'orange', 'Pharmacy Law'),
  ('orange_pharmacy_technician', 'orange', 'Inventory Management'),
  ('orange_pharmacy_technician', 'orange', 'Customer Service'),
  ('orange_massage_therapy', 'orange', 'MBLEx Licensure'),
  ('orange_massage_therapy', 'orange', 'Deep Tissue Massage'),
  ('orange_massage_therapy', 'orange', 'Neuromuscular Therapy'),
  ('orange_massage_therapy', 'orange', 'Anatomy and Kinesiology'),
  ('orange_massage_therapy', 'orange', 'Hydrotherapy'),
  ('orange_massage_therapy', 'orange', 'Client Relations'),
  ('orange_medical_administrative_specialist', 'orange', 'CMAA Certification'),
  ('orange_medical_administrative_specialist', 'orange', 'Medical Transcription'),
  ('orange_medical_administrative_specialist', 'orange', 'Health Information Management'),
  ('orange_medical_administrative_specialist', 'orange', 'Medical Billing/Coding'),
  ('orange_medical_administrative_specialist', 'orange', 'Microsoft Office'),
  ('orange_medical_administrative_specialist', 'orange', 'Patient Communication'),
  ('orange_practical_nursing', 'orange', 'LPN State License'),
  ('orange_practical_nursing', 'orange', 'Pharmacology'),
  ('orange_practical_nursing', 'orange', 'Medical-Surgical Nursing'),
  ('orange_practical_nursing', 'orange', 'Pediatric Nursing'),
  ('orange_practical_nursing', 'orange', 'Geriatric Care'),
  ('orange_practical_nursing', 'orange', 'Patient Advocacy'),
  ('orange_patient_care_assistant', 'orange', 'CNA State License'),
  ('orange_patient_care_assistant', 'orange', 'Vital Signs Monitoring'),
  ('orange_patient_care_assistant', 'orange', 'Activities of Daily Living (ADL)'),
  ('orange_patient_care_assistant', 'orange', 'Patient Hygiene'),
  ('orange_patient_care_assistant', 'orange', 'Basic Nursing Skills'),
  ('orange_patient_care_assistant', 'orange', 'Compassion'),
  ('orange_enterprise_network_and_server_support_technology', 'orange', 'CompTIA Security+'),
  ('orange_enterprise_network_and_server_support_technology', 'orange', 'Cisco CCNA'),
  ('orange_enterprise_network_and_server_support_technology', 'orange', 'Microsoft Certified Systems Administrator'),
  ('orange_enterprise_network_and_server_support_technology', 'orange', 'Server Administration'),
  ('orange_enterprise_network_and_server_support_technology', 'orange', 'Network Configuration'),
  ('orange_enterprise_network_and_server_support_technology', 'orange', 'Virtualization'),
  ('orange_enterprise_desktop_and_mobile_support_technology', 'orange', 'CompTIA A+'),
  ('orange_enterprise_desktop_and_mobile_support_technology', 'orange', 'CompTIA Network+'),
  ('orange_enterprise_desktop_and_mobile_support_technology', 'orange', 'Windows/Linux Configuration'),
  ('orange_enterprise_desktop_and_mobile_support_technology', 'orange', 'Mobile Device Management (MDM)'),
  ('orange_enterprise_desktop_and_mobile_support_technology', 'orange', 'Hardware Troubleshooting'),
  ('orange_enterprise_desktop_and_mobile_support_technology', 'orange', 'Customer Service'),
  ('orange_digital_mediamultimedia_design', 'orange', 'Adobe Creative Cloud'),
  ('orange_digital_mediamultimedia_design', 'orange', 'Adobe Certified Professional'),
  ('orange_digital_mediamultimedia_design', 'orange', 'Graphic Design'),
  ('orange_digital_mediamultimedia_design', 'orange', 'Web Design'),
  ('orange_digital_mediamultimedia_design', 'orange', 'Video Editing'),
  ('orange_digital_mediamultimedia_design', 'orange', 'Visual Communication'),
  ('orange_3d_animation_technology', 'orange', 'Autodesk Maya'),
  ('orange_3d_animation_technology', 'orange', 'Autodesk Certification'),
  ('orange_3d_animation_technology', 'orange', '3D Modeling'),
  ('orange_3d_animation_technology', 'orange', 'Rigging'),
  ('orange_3d_animation_technology', 'orange', 'Texturing'),
  ('orange_3d_animation_technology', 'orange', 'Motion Capture'),
  ('orange_cosmetology', 'orange', 'Florida State Cosmetology License'),
  ('orange_cosmetology', 'orange', 'Hair Design'),
  ('orange_cosmetology', 'orange', 'Chemical Processes'),
  ('orange_cosmetology', 'orange', 'Skin Care'),
  ('orange_cosmetology', 'orange', 'Salon Management'),
  ('orange_cosmetology', 'orange', 'Client Relations'),
  ('orange_professional_culinary_arts_hospitality', 'orange', 'ServSafe Certification'),
  ('orange_professional_culinary_arts_hospitality', 'orange', 'Classical Cooking Techniques'),
  ('orange_professional_culinary_arts_hospitality', 'orange', 'Food Sanitation'),
  ('orange_professional_culinary_arts_hospitality', 'orange', 'Kitchen Management'),
  ('orange_professional_culinary_arts_hospitality', 'orange', 'Menu Planning'),
  ('orange_professional_culinary_arts_hospitality', 'orange', 'Time Management'),
  ('seminole_nursing', 'seminole', 'NCLEX-RN Certification'),
  ('seminole_nursing', 'seminole', 'Patient Assessment'),
  ('seminole_nursing', 'seminole', 'Medication Administration'),
  ('seminole_nursing', 'seminole', 'Clinical Procedures'),
  ('seminole_nursing', 'seminole', 'Critical Thinking'),
  ('seminole_nursing', 'seminole', 'Patient Advocacy'),
  ('seminole_nursing', 'seminole', 'Nursing Leadership'),
  ('seminole_nursing', 'seminole', 'Evidence-Based Practice'),
  ('seminole_nursing', 'seminole', 'Nursing Research'),
  ('seminole_nursing', 'seminole', 'Community Health'),
  ('seminole_nursing', 'seminole', 'Team Management'),
  ('seminole_nursing', 'seminole', 'Strategic Planning'),
  ('seminole_respiratory_care', 'seminole', 'RRT Certification'),
  ('seminole_respiratory_care', 'seminole', 'Cardiopulmonary Physiology'),
  ('seminole_respiratory_care', 'seminole', 'Ventilator Management'),
  ('seminole_respiratory_care', 'seminole', 'Critical Care Medicine'),
  ('seminole_respiratory_care', 'seminole', 'Arterial Blood Gas Analysis'),
  ('seminole_respiratory_care', 'seminole', 'Patient Education'),
  ('seminole_physical_therapist_assistant', 'seminole', 'NPTAE Certification'),
  ('seminole_physical_therapist_assistant', 'seminole', 'Musculoskeletal Rehabilitation'),
  ('seminole_physical_therapist_assistant', 'seminole', 'Neuromuscular Therapy'),
  ('seminole_physical_therapist_assistant', 'seminole', 'Therapeutic Exercise'),
  ('seminole_physical_therapist_assistant', 'seminole', 'Gait Training'),
  ('seminole_physical_therapist_assistant', 'seminole', 'Patient Motivation'),
  ('seminole_health_information_technology', 'seminole', 'RHIT Certification'),
  ('seminole_health_information_technology', 'seminole', 'ICD-10 Coding'),
  ('seminole_health_information_technology', 'seminole', 'CPT Coding'),
  ('seminole_health_information_technology', 'seminole', 'Health Data Analysis'),
  ('seminole_health_information_technology', 'seminole', 'Healthcare Statistics'),
  ('seminole_health_information_technology', 'seminole', 'HIPAA Compliance'),
  ('seminole_health_sciences', 'seminole', 'Healthcare Finance'),
  ('seminole_health_sciences', 'seminole', 'Health Law and Ethics'),
  ('seminole_health_sciences', 'seminole', 'U.S. Healthcare System'),
  ('seminole_health_sciences', 'seminole', 'Clinical Leadership'),
  ('seminole_health_sciences', 'seminole', 'Staff Management'),
  ('seminole_health_sciences', 'seminole', 'Quality Improvement'),
  ('seminole_cybersecurity', 'seminole', 'CompTIA Security+'),
  ('seminole_cybersecurity', 'seminole', 'Certified Ethical Hacker (CEH)'),
  ('seminole_cybersecurity', 'seminole', 'Penetration Testing'),
  ('seminole_cybersecurity', 'seminole', 'Vulnerability Assessment'),
  ('seminole_cybersecurity', 'seminole', 'Network Defense'),
  ('seminole_cybersecurity', 'seminole', 'Incident Response'),
  ('seminole_information_systems_technology_cybersecurity', 'seminole', 'Enterprise Networking'),
  ('seminole_information_systems_technology_cybersecurity', 'seminole', 'Security Analysis'),
  ('seminole_information_systems_technology_cybersecurity', 'seminole', 'Firewall Configuration'),
  ('seminole_information_systems_technology_cybersecurity', 'seminole', 'Intrusion Detection'),
  ('seminole_information_systems_technology_cybersecurity', 'seminole', 'Operating Systems Security'),
  ('seminole_information_systems_technology_cybersecurity', 'seminole', 'Analytical Thinking'),
  ('seminole_information_systems_technology', 'seminole', 'Cybersecurity Operations'),
  ('seminole_information_systems_technology', 'seminole', 'Digital Forensics'),
  ('seminole_information_systems_technology', 'seminole', 'Information Security Management'),
  ('seminole_information_systems_technology', 'seminole', 'Cloud Security'),
  ('seminole_information_systems_technology', 'seminole', 'Risk Assessment'),
  ('seminole_information_systems_technology', 'seminole', 'Leadership'),
  ('seminole_computer_programming_and_analysis', 'seminole', 'JavaScript'),
  ('seminole_computer_programming_and_analysis', 'seminole', 'Python'),
  ('seminole_computer_programming_and_analysis', 'seminole', 'Node.js'),
  ('seminole_computer_programming_and_analysis', 'seminole', 'C++'),
  ('seminole_computer_programming_and_analysis', 'seminole', 'SQL'),
  ('seminole_computer_programming_and_analysis', 'seminole', 'Problem Solving'),
  ('seminole_network_support_technician', 'seminole', 'CompTIA A+'),
  ('seminole_network_support_technician', 'seminole', 'Hardware Troubleshooting'),
  ('seminole_network_support_technician', 'seminole', 'Operating Systems'),
  ('seminole_network_support_technician', 'seminole', 'Ticketing Systems'),
  ('seminole_network_support_technician', 'seminole', 'Customer Service'),
  ('seminole_network_infrastructure', 'seminole', 'CompTIA Network+'),
  ('seminole_network_infrastructure', 'seminole', 'CCNA'),
  ('seminole_network_infrastructure', 'seminole', 'Router Configuration'),
  ('seminole_network_infrastructure', 'seminole', 'Switch Configuration'),
  ('seminole_network_infrastructure', 'seminole', 'Network Troubleshooting'),
  ('seminole_network_systems_technology', 'seminole', 'AWS Fundamentals'),
  ('seminole_network_systems_technology', 'seminole', 'Azure Administration'),
  ('seminole_network_systems_technology', 'seminole', 'Network Infrastructure'),
  ('seminole_network_systems_technology', 'seminole', 'Server Administration'),
  ('seminole_network_systems_technology', 'seminole', 'Cloud Computing'),
  ('seminole_network_systems_technology', 'seminole', 'Documentation'),
  ('seminole_construction_management', 'seminole', 'Blueprint Reading'),
  ('seminole_construction_management', 'seminole', 'Cost Estimating'),
  ('seminole_construction_management', 'seminole', 'Construction Safety'),
  ('seminole_construction_management', 'seminole', 'Materials Management'),
  ('seminole_construction_management', 'seminole', 'Project Scheduling'),
  ('seminole_construction_management', 'seminole', 'Team Coordination'),
  ('seminole_construction', 'seminole', 'General Contractor Licensure'),
  ('seminole_construction', 'seminole', 'Construction Project Management'),
  ('seminole_construction', 'seminole', 'Construction Cost Estimating'),
  ('seminole_construction', 'seminole', 'Construction Materials and Methods'),
  ('seminole_construction', 'seminole', 'Contract Administration'),
  ('seminole_construction', 'seminole', 'Leadership'),
  ('seminole_building_construction_technology', 'seminole', 'Construction Methods'),
  ('seminole_building_construction_technology', 'seminole', 'Building Codes'),
  ('seminole_building_construction_technology', 'seminole', 'Site Safety'),
  ('seminole_building_construction_technology', 'seminole', 'Materials Handling'),
  ('seminole_building_construction_technology', 'seminole', 'Quality Inspection'),
  ('seminole_interior_design', 'seminole', 'AutoCAD'),
  ('seminole_interior_design', 'seminole', 'Revit'),
  ('seminole_interior_design', 'seminole', 'Space Planning'),
  ('seminole_interior_design', 'seminole', 'Visual Presentation'),
  ('seminole_interior_design', 'seminole', 'Color Theory'),
  ('seminole_interior_design', 'seminole', 'Client Communication'),
  ('seminole_interior_design', 'seminole', 'NCIDQ Certification'),
  ('seminole_interior_design', 'seminole', 'Evidence-Based Design'),
  ('seminole_interior_design', 'seminole', 'Human-Centered Design'),
  ('seminole_interior_design', 'seminole', 'Building Codes and Regulations'),
  ('seminole_interior_design', 'seminole', 'Project Management'),
  ('seminole_interior_design', 'seminole', 'Client Presentation'),
  ('seminole_mechatronics', 'seminole', 'PLC Programming'),
  ('seminole_mechatronics', 'seminole', 'Fluid Power Systems'),
  ('seminole_mechatronics', 'seminole', 'Robotics Maintenance'),
  ('seminole_mechatronics', 'seminole', 'Industrial Troubleshooting'),
  ('seminole_mechatronics', 'seminole', 'PMMI Mechatronics Certification'),
  ('seminole_engineering_technology', 'seminole', 'Industrial Processes'),
  ('seminole_engineering_technology', 'seminole', 'Quality Control'),
  ('seminole_engineering_technology', 'seminole', 'Technical Drawing'),
  ('seminole_engineering_technology', 'seminole', 'Equipment Maintenance'),
  ('seminole_engineering_technology', 'seminole', 'Process Improvement'),
  ('seminole_engineering_technology', 'seminole', 'Attention to Detail'),
  ('seminole_automotive_engineering_technology', 'seminole', 'ASE Master Technician Certification'),
  ('seminole_automotive_engineering_technology', 'seminole', 'Ford ASSET / GM ASEP Training'),
  ('seminole_automotive_engineering_technology', 'seminole', 'Hybrid/Electric Vehicle Technology'),
  ('seminole_automotive_engineering_technology', 'seminole', 'Engine Diagnostics'),
  ('seminole_automotive_engineering_technology', 'seminole', 'Automotive Electronics'),
  ('seminole_automotive_engineering_technology', 'seminole', 'Customer Service'),
  ('seminole_criminal_justice_law_enforcement_academy', 'seminole', 'FDLE Certification'),
  ('seminole_criminal_justice_law_enforcement_academy', 'seminole', 'Law Enforcement Procedures'),
  ('seminole_criminal_justice_law_enforcement_academy', 'seminole', 'Firearms Proficiency'),
  ('seminole_criminal_justice_law_enforcement_academy', 'seminole', 'Defensive Tactics'),
  ('seminole_criminal_justice_law_enforcement_academy', 'seminole', 'Report Writing'),
  ('seminole_criminal_justice_law_enforcement_academy', 'seminole', 'Crisis De-escalation'),
  ('seminole_criminal_justice_technology', 'seminole', 'Criminology'),
  ('seminole_criminal_justice_technology', 'seminole', 'Criminal Law'),
  ('seminole_criminal_justice_technology', 'seminole', 'Criminal Investigation'),
  ('seminole_criminal_justice_technology', 'seminole', 'Evidence Collection'),
  ('seminole_criminal_justice_technology', 'seminole', 'Interview Techniques'),
  ('seminole_criminal_justice_technology', 'seminole', 'Critical Thinking'),
  ('seminole_public_safety_administration', 'seminole', 'Public Policy'),
  ('seminole_public_safety_administration', 'seminole', 'Administrative Law'),
  ('seminole_public_safety_administration', 'seminole', 'Crisis Management'),
  ('seminole_public_safety_administration', 'seminole', 'Budget Administration'),
  ('seminole_public_safety_administration', 'seminole', 'Strategic Leadership'),
  ('seminole_public_safety_administration', 'seminole', 'Agency Management'),
  ('seminole_fire_science_technology', 'seminole', 'Fire Officer Supervisor Certification'),
  ('seminole_fire_science_technology', 'seminole', 'Fire Prevention'),
  ('seminole_fire_science_technology', 'seminole', 'Building Construction for Fire Service'),
  ('seminole_fire_science_technology', 'seminole', 'Fire Tactics'),
  ('seminole_fire_science_technology', 'seminole', 'Incident Command'),
  ('seminole_fire_science_technology', 'seminole', 'Team Leadership'),
  ('seminole_legal_assistantparalegal_studies', 'seminole', 'ABA Approved Program'),
  ('seminole_legal_assistantparalegal_studies', 'seminole', 'Legal Research and Writing'),
  ('seminole_legal_assistantparalegal_studies', 'seminole', 'Civil Litigation'),
  ('seminole_legal_assistantparalegal_studies', 'seminole', 'Torts'),
  ('seminole_legal_assistantparalegal_studies', 'seminole', 'Florida E-Filing Portal'),
  ('seminole_legal_assistantparalegal_studies', 'seminole', 'Case Management Software'),
  ('seminole_management_and_organizational_leadership', 'seminole', 'Global Supply Chain Management'),
  ('seminole_management_and_organizational_leadership', 'seminole', 'Human Resources Management'),
  ('seminole_management_and_organizational_leadership', 'seminole', 'Business Finance'),
  ('seminole_management_and_organizational_leadership', 'seminole', 'Organizational Leadership'),
  ('seminole_management_and_organizational_leadership', 'seminole', 'Strategic Planning'),
  ('seminole_management_and_organizational_leadership', 'seminole', 'Change Management'),
  ('seminole_human_resources_administrator', 'seminole', 'SHRM Competencies'),
  ('seminole_human_resources_administrator', 'seminole', 'Employment Law'),
  ('seminole_human_resources_administrator', 'seminole', 'Compensation and Benefits'),
  ('seminole_human_resources_administrator', 'seminole', 'Recruitment'),
  ('seminole_human_resources_administrator', 'seminole', 'HRIS Systems'),
  ('seminole_human_resources_administrator', 'seminole', 'Interpersonal Skills'),
  ('seminole_entrepreneurship', 'seminole', 'Opportunity Analysis'),
  ('seminole_entrepreneurship', 'seminole', 'Entrepreneurial Marketing'),
  ('seminole_entrepreneurship', 'seminole', 'Business Planning'),
  ('seminole_entrepreneurship', 'seminole', 'Financial Management'),
  ('seminole_entrepreneurship', 'seminole', 'Risk Assessment'),
  ('seminole_entrepreneurship', 'seminole', 'Networking'),
  ('seminole_elementary_education', 'seminole', 'Florida Teaching Certification (K-6)'),
  ('seminole_elementary_education', 'seminole', 'Reading Endorsement'),
  ('seminole_elementary_education', 'seminole', 'ESOL Endorsement'),
  ('seminole_elementary_education', 'seminole', 'Lesson Planning'),
  ('seminole_elementary_education', 'seminole', 'Classroom Management'),
  ('seminole_elementary_education', 'seminole', 'Differentiated Instruction'),
  ('seminole_exceptional_student_education', 'seminole', 'Florida ESE Certification (K-12)'),
  ('seminole_exceptional_student_education', 'seminole', 'Reading Endorsement'),
  ('seminole_exceptional_student_education', 'seminole', 'ESOL Endorsement'),
  ('seminole_exceptional_student_education', 'seminole', 'IEP Development'),
  ('seminole_exceptional_student_education', 'seminole', 'Behavior Management'),
  ('seminole_exceptional_student_education', 'seminole', 'Patience and Empathy'),
  ('ucf_civil_engineering', 'ucf', 'AutoCAD Civil 3D'),
  ('ucf_civil_engineering', 'ucf', 'MicroStation'),
  ('ucf_civil_engineering', 'ucf', 'Site Design'),
  ('ucf_civil_engineering', 'ucf', 'Permitting and Compliance'),
  ('ucf_civil_engineering', 'ucf', 'Construction Inspection'),
  ('ucf_civil_engineering', 'ucf', 'Technical Writing'),
  ('ucf_construction_engineering', 'ucf', 'Project Documentation'),
  ('ucf_construction_engineering', 'ucf', 'RFI Management'),
  ('ucf_construction_engineering', 'ucf', 'Submittal Processing'),
  ('ucf_construction_engineering', 'ucf', 'Safety Compliance'),
  ('ucf_construction_engineering', 'ucf', 'Subcontractor Management'),
  ('ucf_construction_engineering', 'ucf', 'Spanish Communication'),
  ('ucf_environmental_engineering', 'ucf', 'HEC-RAS'),
  ('ucf_environmental_engineering', 'ucf', 'ICPR'),
  ('ucf_environmental_engineering', 'ucf', 'SWMM'),
  ('ucf_environmental_engineering', 'ucf', 'Hydraulic Modeling'),
  ('ucf_environmental_engineering', 'ucf', 'Stormwater Management'),
  ('ucf_environmental_engineering', 'ucf', 'Environmental Regulations'),
  ('ucf_photonic_science_and_engineering', 'ucf', 'Optical Design'),
  ('ucf_photonic_science_and_engineering', 'ucf', 'Lens Assembly Design'),
  ('ucf_photonic_science_and_engineering', 'ucf', 'Laser Systems'),
  ('ucf_photonic_science_and_engineering', 'ucf', 'Optical Bench Setup'),
  ('ucf_photonic_science_and_engineering', 'ucf', 'Fiber Optics'),
  ('ucf_photonic_science_and_engineering', 'ucf', 'LiDAR Technology'),
  ('ucf_materials_science_and_engineering', 'ucf', 'Scanning Electron Microscopy (SEM)'),
  ('ucf_materials_science_and_engineering', 'ucf', 'X-Ray Diffraction (XRD)'),
  ('ucf_materials_science_and_engineering', 'ucf', 'Spectroscopy'),
  ('ucf_materials_science_and_engineering', 'ucf', 'Composites Analysis'),
  ('ucf_materials_science_and_engineering', 'ucf', 'Semiconductor Processing'),
  ('ucf_materials_science_and_engineering', 'ucf', 'Corrosion Control'),
  ('ucf_theme_park_and_attraction_management', 'ucf', 'Guest Recovery'),
  ('ucf_theme_park_and_attraction_management', 'ucf', 'Crew Scheduling'),
  ('ucf_theme_park_and_attraction_management', 'ucf', 'Safety Compliance'),
  ('ucf_theme_park_and_attraction_management', 'ucf', 'Bilingual Communication (Spanish)'),
  ('ucf_theme_park_and_attraction_management', 'ucf', 'Conflict Resolution'),
  ('ucf_theme_park_and_attraction_management', 'ucf', 'Operational Leadership'),
  ('ucf_event_management', 'ucf', 'Event Logistics'),
  ('ucf_event_management', 'ucf', 'Vendor Management'),
  ('ucf_event_management', 'ucf', 'Room Block Coordination'),
  ('ucf_event_management', 'ucf', 'Sales and Negotiation'),
  ('ucf_event_management', 'ucf', 'Budget Management'),
  ('ucf_event_management', 'ucf', 'Client Relations'),
  ('ucf_integrated_business', 'ucf', 'Public Speaking'),
  ('ucf_integrated_business', 'ucf', 'Business Presentation'),
  ('ucf_integrated_business', 'ucf', 'Process Improvement'),
  ('ucf_integrated_business', 'ucf', 'Data Analysis'),
  ('ucf_integrated_business', 'ucf', 'Team Collaboration'),
  ('ucf_integrated_business', 'ucf', 'Adaptability'),
  ('ucf_real_estate', 'ucf', 'ARGUS'),
  ('ucf_real_estate', 'ucf', 'Excel Financial Modeling'),
  ('ucf_real_estate', 'ucf', 'Cash Flow Analysis'),
  ('ucf_real_estate', 'ucf', 'Property Valuation'),
  ('ucf_real_estate', 'ucf', 'Market Analysis'),
  ('ucf_real_estate', 'ucf', 'Negotiation'),
  ('ucf_medical_laboratory_sciences', 'ucf', 'Hematology Testing'),
  ('ucf_medical_laboratory_sciences', 'ucf', 'Microbiology'),
  ('ucf_medical_laboratory_sciences', 'ucf', 'Clinical Chemistry'),
  ('ucf_medical_laboratory_sciences', 'ucf', 'ASCP Certification'),
  ('ucf_medical_laboratory_sciences', 'ucf', 'Quality Control'),
  ('ucf_medical_laboratory_sciences', 'ucf', 'Microscopy'),
  ('ucf_biomedical_sciences', 'ucf', 'Clinical Research (CCRP)'),
  ('ucf_biomedical_sciences', 'ucf', 'Phlebotomy'),
  ('ucf_biomedical_sciences', 'ucf', 'Laboratory Techniques'),
  ('ucf_biomedical_sciences', 'ucf', 'Data Collection'),
  ('ucf_biomedical_sciences', 'ucf', 'Scientific Writing'),
  ('ucf_biomedical_sciences', 'ucf', 'Regulatory Compliance'),
  ('ucf_communication_sciences_and_disorders', 'ucf', 'Speech Therapy Techniques'),
  ('ucf_communication_sciences_and_disorders', 'ucf', 'Hearing Assessment'),
  ('ucf_communication_sciences_and_disorders', 'ucf', 'Bilingual Therapy (Spanish)'),
  ('ucf_communication_sciences_and_disorders', 'ucf', 'Patient Documentation'),
  ('ucf_communication_sciences_and_disorders', 'ucf', 'Therapy Plan Implementation'),
  ('ucf_communication_sciences_and_disorders', 'ucf', 'Empathy and Patience'),
  ('ucf_digital_media_and_game_design', 'ucf', 'Unity'),
  ('ucf_digital_media_and_game_design', 'ucf', 'Unreal Engine'),
  ('ucf_digital_media_and_game_design', 'ucf', '3D Modeling'),
  ('ucf_digital_media_and_game_design', 'ucf', 'UI/UX Design'),
  ('ucf_digital_media_and_game_design', 'ucf', 'Game Testing'),
  ('ucf_digital_media_and_game_design', 'ucf', 'Portfolio Development'),
  ('ucf_emerging_media_character_animation', 'ucf', 'Maya'),
  ('ucf_emerging_media_character_animation', 'ucf', 'Blender'),
  ('ucf_emerging_media_character_animation', 'ucf', 'After Effects'),
  ('ucf_emerging_media_character_animation', 'ucf', 'Character Rigging'),
  ('ucf_emerging_media_character_animation', 'ucf', 'Texturing and Lighting'),
  ('ucf_emerging_media_character_animation', 'ucf', 'Storytelling'),
  ('ucf_psychology', 'ucf', 'ABA Therapy'),
  ('ucf_psychology', 'ucf', 'Case Documentation'),
  ('ucf_psychology', 'ucf', 'Bilingual Communication (Spanish)'),
  ('ucf_psychology', 'ucf', 'Crisis Intervention'),
  ('ucf_psychology', 'ucf', 'Active Listening'),
  ('ucf_psychology', 'ucf', 'Data Collection'),
  ('ucf_sociology', 'ucf', 'Research Methods'),
  ('ucf_sociology', 'ucf', 'Data Analysis'),
  ('ucf_sociology', 'ucf', 'Community Engagement'),
  ('ucf_sociology', 'ucf', 'Report Writing'),
  ('ucf_sociology', 'ucf', 'Bilingual Communication (Spanish)'),
  ('ucf_sociology', 'ucf', 'Critical Thinking'),
  ('ucf_history', 'ucf', 'Archival Research'),
  ('ucf_history', 'ucf', 'Grant Writing'),
  ('ucf_history', 'ucf', 'Historical Analysis'),
  ('ucf_history', 'ucf', 'Technical Writing'),
  ('ucf_history', 'ucf', 'Data Synthesis'),
  ('ucf_history', 'ucf', 'Public Presentation'),
  ('ucf_anthropology', 'ucf', 'Archaeological Survey'),
  ('ucf_anthropology', 'ucf', 'GIS Mapping'),
  ('ucf_anthropology', 'ucf', 'Ethnographic Research'),
  ('ucf_anthropology', 'ucf', 'Artifact Analysis'),
  ('ucf_anthropology', 'ucf', 'Field Documentation'),
  ('ucf_anthropology', 'ucf', 'Cross-Cultural Communication'),
  ('ucf_political_science', 'ucf', 'Policy Research'),
  ('ucf_political_science', 'ucf', 'Legislative Analysis'),
  ('ucf_political_science', 'ucf', 'Public Speaking'),
  ('ucf_political_science', 'ucf', 'Campaign Management'),
  ('ucf_political_science', 'ucf', 'Constituent Relations'),
  ('ucf_political_science', 'ucf', 'Political Writing'),
  ('ucf_social_work', 'ucf', 'Crisis Intervention'),
  ('ucf_social_work', 'ucf', 'Case Management'),
  ('ucf_social_work', 'ucf', 'Bilingual Communication (Spanish)'),
  ('ucf_social_work', 'ucf', 'Family Assessment'),
  ('ucf_social_work', 'ucf', 'Child Welfare Regulations'),
  ('ucf_social_work', 'ucf', 'Advocacy'),
  ('valencia_computing_technology_software_development', 'valencia', 'Python'),
  ('valencia_computing_technology_software_development', 'valencia', 'Java'),
  ('valencia_computing_technology_software_development', 'valencia', 'Cloud Architecture (AWS)'),
  ('valencia_computing_technology_software_development', 'valencia', 'Machine Learning Concepts'),
  ('valencia_computing_technology_software_development', 'valencia', 'Agile Methodology'),
  ('valencia_computing_technology_software_development', 'valencia', 'Problem Solving'),
  ('valencia_computer_information_technology', 'valencia', 'Network Configuration'),
  ('valencia_computer_information_technology', 'valencia', 'Windows Server Admin'),
  ('valencia_computer_information_technology', 'valencia', 'Virtualization'),
  ('valencia_computer_information_technology', 'valencia', 'Hardware Diagnostics'),
  ('valencia_computer_information_technology', 'valencia', 'Customer Service'),
  ('valencia_computer_programming_analysis', 'valencia', 'C#'),
  ('valencia_computer_programming_analysis', 'valencia', 'C++'),
  ('valencia_computer_programming_analysis', 'valencia', 'Java'),
  ('valencia_computer_programming_analysis', 'valencia', 'SQL Querying'),
  ('valencia_computer_programming_analysis', 'valencia', 'HTML5 / CSS3'),
  ('valencia_computer_programming_analysis', 'valencia', 'Debugging'),
  ('valencia_computer_programming_analysis', 'valencia', 'Algorithm Logic'),
  ('valencia_network_engineering_technology', 'valencia', 'Cisco IOS'),
  ('valencia_network_engineering_technology', 'valencia', 'Subnetting'),
  ('valencia_network_engineering_technology', 'valencia', 'Network Security'),
  ('valencia_network_engineering_technology', 'valencia', 'Protocol Analysis'),
  ('valencia_network_engineering_technology', 'valencia', 'Structured Cabling'),
  ('valencia_cyber_security', 'valencia', 'Vulnerability Scanning'),
  ('valencia_cyber_security', 'valencia', 'Risk Assessment'),
  ('valencia_cyber_security', 'valencia', 'Incident Response'),
  ('valencia_cyber_security', 'valencia', 'Compliance'),
  ('valencia_cyber_security', 'valencia', 'Linux Security'),
  ('valencia_database_administration', 'valencia', 'SQL'),
  ('valencia_database_administration', 'valencia', 'Backup & Recovery'),
  ('valencia_database_administration', 'valencia', 'Data Modeling'),
  ('valencia_database_administration', 'valencia', 'Database Security'),
  ('valencia_database_administration', 'valencia', 'Performance Tuning'),
  ('valencia_it_support_specialist', 'valencia', 'Hardware Repair'),
  ('valencia_it_support_specialist', 'valencia', 'OS Installation'),
  ('valencia_it_support_specialist', 'valencia', 'Ticketing Systems'),
  ('valencia_it_support_specialist', 'valencia', 'Remote Support'),
  ('valencia_it_support_specialist', 'valencia', 'Customer Service'),
  ('valencia_network_support_technician', 'valencia', 'Cabling Standards'),
  ('valencia_network_support_technician', 'valencia', 'Basic Routing'),
  ('valencia_network_support_technician', 'valencia', 'Connectivity Diagnostics'),
  ('valencia_network_support_technician', 'valencia', 'Network Mapping'),
  ('valencia_network_support_technician', 'valencia', 'Switch Configuration'),
  ('valencia_web_development', 'valencia', 'HTML5 / CSS3'),
  ('valencia_web_development', 'valencia', 'JavaScript (Basic)'),
  ('valencia_web_development', 'valencia', 'CMS Management'),
  ('valencia_web_development', 'valencia', 'Responsive Design'),
  ('valencia_web_development', 'valencia', 'SEO Basics'),
  ('valencia_electrical_computer_engineering_technology', 'valencia', 'Circuit Analysis'),
  ('valencia_electrical_computer_engineering_technology', 'valencia', 'PLC Programming'),
  ('valencia_electrical_computer_engineering_technology', 'valencia', 'Cleanroom Protocol'),
  ('valencia_electrical_computer_engineering_technology', 'valencia', 'Matlab/Simulink'),
  ('valencia_electrical_computer_engineering_technology', 'valencia', 'Technical Writing'),
  ('valencia_electrical_engineering_technology', 'valencia', 'Soldering'),
  ('valencia_electrical_engineering_technology', 'valencia', 'Oscilloscope Usage'),
  ('valencia_electrical_engineering_technology', 'valencia', 'Schematic Reading'),
  ('valencia_electrical_engineering_technology', 'valencia', 'Multimeter Proficiency'),
  ('valencia_electrical_engineering_technology', 'valencia', 'Troubleshooting Logic'),
  ('valencia_engineering_technology', 'valencia', 'AutoCAD / SolidWorks'),
  ('valencia_engineering_technology', 'valencia', 'Metrology'),
  ('valencia_engineering_technology', 'valencia', 'Lean Manufacturing'),
  ('valencia_engineering_technology', 'valencia', 'Hydraulics/Pneumatics'),
  ('valencia_engineering_technology', 'valencia', 'Materials Science'),
  ('valencia_automotive_service_technology', 'valencia', 'Engine Diagnostics'),
  ('valencia_automotive_service_technology', 'valencia', 'Brake Systems'),
  ('valencia_automotive_service_technology', 'valencia', 'Electrical Systems'),
  ('valencia_automotive_service_technology', 'valencia', 'Suspension & Steering'),
  ('valencia_automotive_service_technology', 'valencia', 'Safety Protocols'),
  ('valencia_electrician', 'valencia', 'NEC Code Compliance'),
  ('valencia_electrician', 'valencia', 'Circuit Installation'),
  ('valencia_electrician', 'valencia', 'Blueprint Reading'),
  ('valencia_electrician', 'valencia', 'Conduit Bending'),
  ('valencia_electrician', 'valencia', 'Safety/Lockout-Tagout'),
  ('valencia_hvacr_technician', 'valencia', 'EPA Certification'),
  ('valencia_hvacr_technician', 'valencia', 'Electrical Troubleshooting'),
  ('valencia_hvacr_technician', 'valencia', 'Brazing/Soldering'),
  ('valencia_hvacr_technician', 'valencia', 'Airflow Dynamics'),
  ('valencia_hvacr_technician', 'valencia', 'Customer Service'),
  ('valencia_welding_technology', 'valencia', 'Welding Processes'),
  ('valencia_welding_technology', 'valencia', 'Blueprint Reading'),
  ('valencia_welding_technology', 'valencia', 'Metal Properties'),
  ('valencia_welding_technology', 'valencia', 'Thermal Cutting'),
  ('valencia_welding_technology', 'valencia', 'Quality Control'),
  ('valencia_nursing', 'valencia', 'Evidence-Based Practice'),
  ('valencia_nursing', 'valencia', 'Leadership'),
  ('valencia_nursing', 'valencia', 'Health Informatics'),
  ('valencia_nursing', 'valencia', 'Community Health'),
  ('valencia_nursing', 'valencia', 'Critical Thinking'),
  ('valencia_health_services_administration', 'valencia', 'Healthcare Law/Ethics'),
  ('valencia_health_services_administration', 'valencia', 'Financial Management'),
  ('valencia_health_services_administration', 'valencia', 'Human Resources'),
  ('valencia_health_services_administration', 'valencia', 'Strategic Planning'),
  ('valencia_health_services_administration', 'valencia', 'EHR Systems'),
  ('valencia_nursing', 'valencia', 'Patient Assessment'),
  ('valencia_nursing', 'valencia', 'Medication Administration'),
  ('valencia_nursing', 'valencia', 'Clinical Procedures'),
  ('valencia_nursing', 'valencia', 'Critical Thinking'),
  ('valencia_nursing', 'valencia', 'Patient Advocacy'),
  ('valencia_diagnostic_medical_sonography', 'valencia', 'Anatomy/Physiology'),
  ('valencia_diagnostic_medical_sonography', 'valencia', 'Physics of Sound'),
  ('valencia_diagnostic_medical_sonography', 'valencia', 'Patient Positioning'),
  ('valencia_diagnostic_medical_sonography', 'valencia', 'Pathology Recognition'),
  ('valencia_diagnostic_medical_sonography', 'valencia', 'Image Annotation'),
  ('valencia_dental_hygiene', 'valencia', 'Periodontal Therapy'),
  ('valencia_dental_hygiene', 'valencia', 'Dental Radiography'),
  ('valencia_dental_hygiene', 'valencia', 'Patient Education'),
  ('valencia_dental_hygiene', 'valencia', 'Infection Control'),
  ('valencia_dental_hygiene', 'valencia', 'Local Anesthesia'),
  ('valencia_health_information_technology', 'valencia', 'ICD-10 / CPT Coding'),
  ('valencia_health_information_technology', 'valencia', 'EHR Management'),
  ('valencia_health_information_technology', 'valencia', 'Data Privacy'),
  ('valencia_health_information_technology', 'valencia', 'Medical Terminology'),
  ('valencia_health_information_technology', 'valencia', 'Data Analysis'),
  ('valencia_radiography', 'valencia', 'Radiation Safety'),
  ('valencia_radiography', 'valencia', 'Patient Positioning'),
  ('valencia_radiography', 'valencia', 'Anatomy'),
  ('valencia_radiography', 'valencia', 'Equipment Operation'),
  ('valencia_radiography', 'valencia', 'Image Evaluation'),
  ('valencia_respiratory_care', 'valencia', 'Ventilator Management'),
  ('valencia_respiratory_care', 'valencia', 'Arterial Blood Gas'),
  ('valencia_respiratory_care', 'valencia', 'Cardiopulmonary Physiology'),
  ('valencia_respiratory_care', 'valencia', 'Airway Management'),
  ('valencia_respiratory_care', 'valencia', 'Patient Education'),
  ('valencia_physical_therapist_assistant', 'valencia', 'Therapeutic Exercise'),
  ('valencia_physical_therapist_assistant', 'valencia', 'Manual Therapy'),
  ('valencia_physical_therapist_assistant', 'valencia', 'Gait Training'),
  ('valencia_physical_therapist_assistant', 'valencia', 'Documentation'),
  ('valencia_physical_therapist_assistant', 'valencia', 'Modalities'),
  ('valencia_emergency_medical_services', 'valencia', 'Advanced Life Support'),
  ('valencia_emergency_medical_services', 'valencia', 'Pharmacology'),
  ('valencia_emergency_medical_services', 'valencia', 'Triage'),
  ('valencia_emergency_medical_services', 'valencia', 'Crisis Management'),
  ('valencia_emergency_medical_services', 'valencia', 'Patient Transport'),
  ('valencia_medical_billing_and_coding', 'valencia', 'ICD-10 / CPT'),
  ('valencia_medical_billing_and_coding', 'valencia', 'Insurance Verification'),
  ('valencia_medical_billing_and_coding', 'valencia', 'Billing Software'),
  ('valencia_medical_billing_and_coding', 'valencia', 'Anatomy/Terminology'),
  ('valencia_medical_billing_and_coding', 'valencia', 'Attention to Detail'),
  ('valencia_medical_office_administration', 'valencia', 'Medical Terminology'),
  ('valencia_medical_office_administration', 'valencia', 'HIPAA Compliance'),
  ('valencia_medical_office_administration', 'valencia', 'Scheduling Software'),
  ('valencia_medical_office_administration', 'valencia', 'Customer Service'),
  ('valencia_medical_office_administration', 'valencia', 'Office Systems'),
  ('valencia_phlebotomy', 'valencia', 'Venipuncture'),
  ('valencia_phlebotomy', 'valencia', 'Specimen Handling'),
  ('valencia_phlebotomy', 'valencia', 'Infection Control'),
  ('valencia_phlebotomy', 'valencia', 'Patient Interaction'),
  ('valencia_phlebotomy', 'valencia', 'Safety Compliance'),
  ('valencia_practical_nursing', 'valencia', 'Vitals Monitoring'),
  ('valencia_practical_nursing', 'valencia', 'Patient Hygiene'),
  ('valencia_practical_nursing', 'valencia', 'Medication Administration'),
  ('valencia_practical_nursing', 'valencia', 'Wound Care'),
  ('valencia_practical_nursing', 'valencia', 'Documentation'),
  ('valencia_business_organizational_leadership', 'valencia', 'Strategic Planning'),
  ('valencia_business_organizational_leadership', 'valencia', 'Data Analytics'),
  ('valencia_business_organizational_leadership', 'valencia', 'Conflict Resolution'),
  ('valencia_business_organizational_leadership', 'valencia', 'Change Management'),
  ('valencia_business_organizational_leadership', 'valencia', 'Digital Recruitment'),
  ('valencia_accounting_technology', 'valencia', 'QuickBooks / Excel'),
  ('valencia_accounting_technology', 'valencia', 'Tax Regulation'),
  ('valencia_accounting_technology', 'valencia', 'General Ledger'),
  ('valencia_accounting_technology', 'valencia', 'Financial Reporting'),
  ('valencia_accounting_technology', 'valencia', 'Attention to Detail'),
  ('valencia_business_administration', 'valencia', 'Business Communication'),
  ('valencia_business_administration', 'valencia', 'Marketing Principles'),
  ('valencia_business_administration', 'valencia', 'Team Leadership'),
  ('valencia_business_administration', 'valencia', 'Office Software'),
  ('valencia_business_administration', 'valencia', 'Financial Basics'),
  ('valencia_office_administration', 'valencia', 'Scheduling'),
  ('valencia_office_administration', 'valencia', 'Microsoft Office'),
  ('valencia_office_administration', 'valencia', 'Event Planning'),
  ('valencia_office_administration', 'valencia', 'Office Systems'),
  ('valencia_office_administration', 'valencia', 'Communication'),
  ('valencia_public_safety_administration', 'valencia', 'Grant Administration'),
  ('valencia_public_safety_administration', 'valencia', 'Public Policy'),
  ('valencia_public_safety_administration', 'valencia', 'Incident Command'),
  ('valencia_public_safety_administration', 'valencia', 'Budgeting'),
  ('valencia_public_safety_administration', 'valencia', 'HR Management'),
  ('valencia_fire_science_technology', 'valencia', 'Fire Dynamics'),
  ('valencia_fire_science_technology', 'valencia', 'Building Construction'),
  ('valencia_fire_science_technology', 'valencia', 'Hazardous Materials'),
  ('valencia_fire_science_technology', 'valencia', 'Fire Prevention'),
  ('valencia_fire_science_technology', 'valencia', 'Tactics & Strategy'),
  ('valencia_paralegal_studies', 'valencia', 'Legal Research'),
  ('valencia_paralegal_studies', 'valencia', 'Legal Writing'),
  ('valencia_paralegal_studies', 'valencia', 'Civil Litigation'),
  ('valencia_paralegal_studies', 'valencia', 'E-Filing'),
  ('valencia_paralegal_studies', 'valencia', 'Case Management'),
  ('valencia_legal_assisting', 'valencia', 'Legal Terminology'),
  ('valencia_legal_assisting', 'valencia', 'Office Management'),
  ('valencia_legal_assisting', 'valencia', 'Document Prep'),
  ('valencia_legal_assisting', 'valencia', 'Ethics'),
  ('valencia_legal_assisting', 'valencia', 'Research'),
  ('valencia_emergency_medical_technician', 'valencia', 'CPR / First Aid'),
  ('valencia_emergency_medical_technician', 'valencia', 'Patient Assessment'),
  ('valencia_emergency_medical_technician', 'valencia', 'Transport'),
  ('valencia_emergency_medical_technician', 'valencia', 'Vitals'),
  ('valencia_emergency_medical_technician', 'valencia', 'Documentation'),
  ('valencia_fire_fighter', 'valencia', 'Physical Fitness'),
  ('valencia_fire_fighter', 'valencia', 'PPE Usage'),
  ('valencia_fire_fighter', 'valencia', 'Hose Handling'),
  ('valencia_fire_fighter', 'valencia', 'Search & Rescue'),
  ('valencia_fire_fighter', 'valencia', 'Ladder Operations'),
  ('valencia_culinary_management', 'valencia', 'Menu Planning'),
  ('valencia_culinary_management', 'valencia', 'Food Safety'),
  ('valencia_culinary_management', 'valencia', 'Culinary Techniques'),
  ('valencia_culinary_management', 'valencia', 'Inventory Control'),
  ('valencia_culinary_management', 'valencia', 'Staff Supervision'),
  ('valencia_hospitality_tourism_management', 'valencia', 'Customer Service'),
  ('valencia_hospitality_tourism_management', 'valencia', 'Hospitality Law'),
  ('valencia_hospitality_tourism_management', 'valencia', 'PMS Systems'),
  ('valencia_hospitality_tourism_management', 'valencia', 'Revenue Management'),
  ('valencia_hospitality_tourism_management', 'valencia', 'Event Logistics'),
  ('valencia_film_production_technology', 'valencia', 'Cinematography'),
  ('valencia_film_production_technology', 'valencia', 'Video Editing'),
  ('valencia_film_production_technology', 'valencia', 'Set Protocol'),
  ('valencia_film_production_technology', 'valencia', 'Sound Recording'),
  ('valencia_film_production_technology', 'valencia', 'Production Management'),
  ('valencia_graphic_design_technology', 'valencia', 'Adobe Suite'),
  ('valencia_graphic_design_technology', 'valencia', 'Typography'),
  ('valencia_graphic_design_technology', 'valencia', 'Branding'),
  ('valencia_graphic_design_technology', 'valencia', 'Print Production'),
  ('valencia_graphic_design_technology', 'valencia', 'Web Design'),
  ('valencia_interior_design', 'valencia', 'Space Planning'),
  ('valencia_interior_design', 'valencia', 'CAD / Revit'),
  ('valencia_interior_design', 'valencia', 'Color Theory'),
  ('valencia_interior_design', 'valencia', 'Building Codes'),
  ('valencia_interior_design', 'valencia', 'Client Presentation'),
  ('valencia_culinary_arts', 'valencia', 'Knife Skills'),
  ('valencia_culinary_arts', 'valencia', 'Cooking Methods'),
  ('valencia_culinary_arts', 'valencia', 'Sanitation'),
  ('valencia_culinary_arts', 'valencia', 'Mise en Place'),
  ('valencia_culinary_arts', 'valencia', 'Recipe Follow'),
  ('valencia_digital_mediamultimedia', 'valencia', 'Adobe Suite'),
  ('valencia_digital_mediamultimedia', 'valencia', 'Video Editing'),
  ('valencia_digital_mediamultimedia', 'valencia', 'Storyboarding'),
  ('valencia_digital_mediamultimedia', 'valencia', 'Social Media'),
  ('valencia_digital_mediamultimedia', 'valencia', 'Graphic Design'),
  ('valencia_early_childhood_education', 'valencia', 'Child Development'),
  ('valencia_early_childhood_education', 'valencia', 'Curriculum'),
  ('valencia_early_childhood_education', 'valencia', 'Classroom Management'),
  ('valencia_early_childhood_education', 'valencia', 'Observation'),
  ('valencia_early_childhood_education', 'valencia', 'Family Communication'),
  ('valencia_early_childhood_education', 'valencia', 'Supervision'),
  ('valencia_early_childhood_education', 'valencia', 'Play Facilitation'),
  ('valencia_early_childhood_education', 'valencia', 'Hygiene'),
  ('valencia_early_childhood_education', 'valencia', 'Behavior Management'),
  ('valencia_early_childhood_education', 'valencia', 'Regulations'),
  ('valencia_human_services', 'valencia', 'Crisis Intervention'),
  ('valencia_human_services', 'valencia', 'Documentation'),
  ('valencia_human_services', 'valencia', 'Active Listening'),
  ('valencia_human_services', 'valencia', 'Ethics'),
  ('valencia_human_services', 'valencia', 'Resource Referral')
) AS links(program_key, school, skill_name)
JOIN skills sk ON sk.name = links.skill_name
ON CONFLICT (program_key, school, skill_id) DO NOTHING;
